//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.ListaNegraService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaNegra", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class ListaNegra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AUDUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BITCURPOKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INTIDDISPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int INTLISTANEGRAIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHAPELLIDOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHAPMATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHAPPATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHCURPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHDEPENDENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHESTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHFECHANACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHGENEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHIDQEQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHIDRELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHIMSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHINGRESOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHISSSTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHNOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHNOMCOMPLETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHPARENTESCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHPUESTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRAZONSOCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRFCMORALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHTIPOLISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHTIPOLISTANEGRAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iProveedorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchCadenaNMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchCadenaNPMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUDUSUARIO {
            get {
                return this.AUDUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.AUDUSUARIOField, value) != true)) {
                    this.AUDUSUARIOField = value;
                    this.RaisePropertyChanged("AUDUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BITCURPOK {
            get {
                return this.BITCURPOKField;
            }
            set {
                if ((object.ReferenceEquals(this.BITCURPOKField, value) != true)) {
                    this.BITCURPOKField = value;
                    this.RaisePropertyChanged("BITCURPOK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INTIDDISPO {
            get {
                return this.INTIDDISPOField;
            }
            set {
                if ((object.ReferenceEquals(this.INTIDDISPOField, value) != true)) {
                    this.INTIDDISPOField = value;
                    this.RaisePropertyChanged("INTIDDISPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int INTLISTANEGRAID {
            get {
                return this.INTLISTANEGRAIDField;
            }
            set {
                if ((this.INTLISTANEGRAIDField.Equals(value) != true)) {
                    this.INTLISTANEGRAIDField = value;
                    this.RaisePropertyChanged("INTLISTANEGRAID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHAPELLIDOS {
            get {
                return this.VCHAPELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHAPELLIDOSField, value) != true)) {
                    this.VCHAPELLIDOSField = value;
                    this.RaisePropertyChanged("VCHAPELLIDOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHAPMATERNO {
            get {
                return this.VCHAPMATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHAPMATERNOField, value) != true)) {
                    this.VCHAPMATERNOField = value;
                    this.RaisePropertyChanged("VCHAPMATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHAPPATERNO {
            get {
                return this.VCHAPPATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHAPPATERNOField, value) != true)) {
                    this.VCHAPPATERNOField = value;
                    this.RaisePropertyChanged("VCHAPPATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHCURP {
            get {
                return this.VCHCURPField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHCURPField, value) != true)) {
                    this.VCHCURPField = value;
                    this.RaisePropertyChanged("VCHCURP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHDEPENDENCIA {
            get {
                return this.VCHDEPENDENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHDEPENDENCIAField, value) != true)) {
                    this.VCHDEPENDENCIAField = value;
                    this.RaisePropertyChanged("VCHDEPENDENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHENTIDAD {
            get {
                return this.VCHENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHENTIDADField, value) != true)) {
                    this.VCHENTIDADField = value;
                    this.RaisePropertyChanged("VCHENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHESTATUS {
            get {
                return this.VCHESTATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHESTATUSField, value) != true)) {
                    this.VCHESTATUSField = value;
                    this.RaisePropertyChanged("VCHESTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHFECHANAC {
            get {
                return this.VCHFECHANACField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHFECHANACField, value) != true)) {
                    this.VCHFECHANACField = value;
                    this.RaisePropertyChanged("VCHFECHANAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHGENERO {
            get {
                return this.VCHGENEROField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHGENEROField, value) != true)) {
                    this.VCHGENEROField = value;
                    this.RaisePropertyChanged("VCHGENERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHIDQEQ {
            get {
                return this.VCHIDQEQField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHIDQEQField, value) != true)) {
                    this.VCHIDQEQField = value;
                    this.RaisePropertyChanged("VCHIDQEQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHIDREL {
            get {
                return this.VCHIDRELField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHIDRELField, value) != true)) {
                    this.VCHIDRELField = value;
                    this.RaisePropertyChanged("VCHIDREL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHIMSS {
            get {
                return this.VCHIMSSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHIMSSField, value) != true)) {
                    this.VCHIMSSField = value;
                    this.RaisePropertyChanged("VCHIMSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHINGRESOS {
            get {
                return this.VCHINGRESOSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHINGRESOSField, value) != true)) {
                    this.VCHINGRESOSField = value;
                    this.RaisePropertyChanged("VCHINGRESOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHISSSTE {
            get {
                return this.VCHISSSTEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHISSSTEField, value) != true)) {
                    this.VCHISSSTEField = value;
                    this.RaisePropertyChanged("VCHISSSTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHNOMBRE {
            get {
                return this.VCHNOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHNOMBREField, value) != true)) {
                    this.VCHNOMBREField = value;
                    this.RaisePropertyChanged("VCHNOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHNOMCOMPLETO {
            get {
                return this.VCHNOMCOMPLETOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHNOMCOMPLETOField, value) != true)) {
                    this.VCHNOMCOMPLETOField = value;
                    this.RaisePropertyChanged("VCHNOMCOMPLETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHPARENTESCO {
            get {
                return this.VCHPARENTESCOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHPARENTESCOField, value) != true)) {
                    this.VCHPARENTESCOField = value;
                    this.RaisePropertyChanged("VCHPARENTESCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHPUESTO {
            get {
                return this.VCHPUESTOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHPUESTOField, value) != true)) {
                    this.VCHPUESTOField = value;
                    this.RaisePropertyChanged("VCHPUESTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHRAZONSOCIAL {
            get {
                return this.VCHRAZONSOCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRAZONSOCIALField, value) != true)) {
                    this.VCHRAZONSOCIALField = value;
                    this.RaisePropertyChanged("VCHRAZONSOCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHRFC {
            get {
                return this.VCHRFCField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRFCField, value) != true)) {
                    this.VCHRFCField = value;
                    this.RaisePropertyChanged("VCHRFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHRFCMORAL {
            get {
                return this.VCHRFCMORALField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRFCMORALField, value) != true)) {
                    this.VCHRFCMORALField = value;
                    this.RaisePropertyChanged("VCHRFCMORAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHTIPOLISTA {
            get {
                return this.VCHTIPOLISTAField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHTIPOLISTAField, value) != true)) {
                    this.VCHTIPOLISTAField = value;
                    this.RaisePropertyChanged("VCHTIPOLISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHTIPOLISTANEGRA {
            get {
                return this.VCHTIPOLISTANEGRAField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHTIPOLISTANEGRAField, value) != true)) {
                    this.VCHTIPOLISTANEGRAField = value;
                    this.RaisePropertyChanged("VCHTIPOLISTANEGRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iProveedorId {
            get {
                return this.iProveedorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.iProveedorIdField, value) != true)) {
                    this.iProveedorIdField = value;
                    this.RaisePropertyChanged("iProveedorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCadenaNMP {
            get {
                return this.vchCadenaNMPField;
            }
            set {
                if ((object.ReferenceEquals(this.vchCadenaNMPField, value) != true)) {
                    this.vchCadenaNMPField = value;
                    this.RaisePropertyChanged("vchCadenaNMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCadenaNPM {
            get {
                return this.vchCadenaNPMField;
            }
            set {
                if ((object.ReferenceEquals(this.vchCadenaNPMField, value) != true)) {
                    this.vchCadenaNPMField = value;
                    this.RaisePropertyChanged("vchCadenaNPM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ListaNegraService.ListaNegra))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ListaNegraService.SistemasPLD[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ListaNegraService.SistemasPLD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ListaNegraService.Proveedor[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ListaNegraService.Proveedor))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceOk {
            get {
                return this.ServiceOkField;
            }
            set {
                if ((this.ServiceOkField.Equals(value) != true)) {
                    this.ServiceOkField = value;
                    this.RaisePropertyChanged("ServiceOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemasPLD", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class SistemasPLD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int confField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> sintSistemaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int conf {
            get {
                return this.confField;
            }
            set {
                if ((this.confField.Equals(value) != true)) {
                    this.confField = value;
                    this.RaisePropertyChanged("conf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> sintSistemaID {
            get {
                return this.sintSistemaIDField;
            }
            set {
                if ((this.sintSistemaIDField.Equals(value) != true)) {
                    this.sintSistemaIDField = value;
                    this.RaisePropertyChanged("sintSistemaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchDescripcion {
            get {
                return this.vchDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.vchDescripcionField, value) != true)) {
                    this.vchDescripcionField = value;
                    this.RaisePropertyChanged("vchDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombre {
            get {
                return this.vchNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreField, value) != true)) {
                    this.vchNombreField = value;
                    this.RaisePropertyChanged("vchNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iProveedorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iEstatus {
            get {
                return this.iEstatusField;
            }
            set {
                if ((this.iEstatusField.Equals(value) != true)) {
                    this.iEstatusField = value;
                    this.RaisePropertyChanged("iEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iProveedorId {
            get {
                return this.iProveedorIdField;
            }
            set {
                if ((this.iProveedorIdField.Equals(value) != true)) {
                    this.iProveedorIdField = value;
                    this.RaisePropertyChanged("iProveedorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombre {
            get {
                return this.strNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombreField, value) != true)) {
                    this.strNombreField = value;
                    this.RaisePropertyChanged("strNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListaNegraService.IListaNegraServices")]
    public interface IListaNegraServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/InsertarListaNegra", ReplyAction="http://tempuri.org/IListaNegraServices/InsertarListaNegraResponse")]
        BIM.PLD.Website.ListaNegraService.ServiceResult InsertarListaNegra(BIM.PLD.Website.ListaNegraService.ListaNegra oListaNegra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/CargaListasNegras", ReplyAction="http://tempuri.org/IListaNegraServices/CargaListasNegrasResponse")]
        BIM.PLD.Website.ListaNegraService.ServiceResult CargaListasNegras(int iProveedorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/ListarSistemasPLD", ReplyAction="http://tempuri.org/IListaNegraServices/ListarSistemasPLDResponse")]
        BIM.PLD.Website.ListaNegraService.SistemasPLD[] ListarSistemasPLD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/almacenarArchivo", ReplyAction="http://tempuri.org/IListaNegraServices/almacenarArchivoResponse")]
        BIM.PLD.Website.ListaNegraService.ServiceResult almacenarArchivo(string fuente, string destino, string archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/ListarProveedores", ReplyAction="http://tempuri.org/IListaNegraServices/ListarProveedoresResponse")]
        BIM.PLD.Website.ListaNegraService.Proveedor[] ListarProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaNegraServices/insertarProveedor", ReplyAction="http://tempuri.org/IListaNegraServices/insertarProveedorResponse")]
        BIM.PLD.Website.ListaNegraService.ServiceResult insertarProveedor(string proveedor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaNegraServicesChannel : BIM.PLD.Website.ListaNegraService.IListaNegraServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaNegraServicesClient : System.ServiceModel.ClientBase<BIM.PLD.Website.ListaNegraService.IListaNegraServices>, BIM.PLD.Website.ListaNegraService.IListaNegraServices {
        
        public ListaNegraServicesClient() {
        }
        
        public ListaNegraServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListaNegraServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaNegraServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaNegraServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.ListaNegraService.ServiceResult InsertarListaNegra(BIM.PLD.Website.ListaNegraService.ListaNegra oListaNegra) {
            return base.Channel.InsertarListaNegra(oListaNegra);
        }
        
        public BIM.PLD.Website.ListaNegraService.ServiceResult CargaListasNegras(int iProveedorId) {
            return base.Channel.CargaListasNegras(iProveedorId);
        }
        
        public BIM.PLD.Website.ListaNegraService.SistemasPLD[] ListarSistemasPLD() {
            return base.Channel.ListarSistemasPLD();
        }
        
        public BIM.PLD.Website.ListaNegraService.ServiceResult almacenarArchivo(string fuente, string destino, string archivo) {
            return base.Channel.almacenarArchivo(fuente, destino, archivo);
        }
        
        public BIM.PLD.Website.ListaNegraService.Proveedor[] ListarProveedores() {
            return base.Channel.ListarProveedores();
        }
        
        public BIM.PLD.Website.ListaNegraService.ServiceResult insertarProveedor(string proveedor) {
            return base.Channel.insertarProveedor(proveedor);
        }
    }
}
