//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.wsDocumentServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileRequest", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class FileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPathFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFileName {
            get {
                return this.strFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strFileNameField, value) != true)) {
                    this.strFileNameField = value;
                    this.RaisePropertyChanged("strFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFileType {
            get {
                return this.strFileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.strFileTypeField, value) != true)) {
                    this.strFileTypeField = value;
                    this.RaisePropertyChanged("strFileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPathFile {
            get {
                return this.strPathFileField;
            }
            set {
                if ((object.ReferenceEquals(this.strPathFileField, value) != true)) {
                    this.strPathFileField = value;
                    this.RaisePropertyChanged("strPathFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileResponse", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class FileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] btFIleStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] btFIleStream {
            get {
                return this.btFIleStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.btFIleStreamField, value) != true)) {
                    this.btFIleStreamField = value;
                    this.RaisePropertyChanged("btFIleStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strError {
            get {
                return this.strErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.strErrorField, value) != true)) {
                    this.strErrorField = value;
                    this.RaisePropertyChanged("strError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidatePathRequest", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class ValidatePathRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPathFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPathFile {
            get {
                return this.strPathFileField;
            }
            set {
                if ((object.ReferenceEquals(this.strPathFileField, value) != true)) {
                    this.strPathFileField = value;
                    this.RaisePropertyChanged("strPathFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateResponse", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class ValidateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blnExistFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blnExistFile {
            get {
                return this.blnExistFileField;
            }
            set {
                if ((this.blnExistFileField.Equals(value) != true)) {
                    this.blnExistFileField = value;
                    this.RaisePropertyChanged("blnExistFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strResult {
            get {
                return this.strResultField;
            }
            set {
                if ((object.ReferenceEquals(this.strResultField, value) != true)) {
                    this.strResultField = value;
                    this.RaisePropertyChanged("strResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteFileInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class RemoteFileInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strServerPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strServerPath {
            get {
                return this.strServerPathField;
            }
            set {
                if ((object.ReferenceEquals(this.strServerPathField, value) != true)) {
                    this.strServerPathField = value;
                    this.RaisePropertyChanged("strServerPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadFileResponse", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class UploadFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUploadResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUploadResult {
            get {
                return this.strUploadResultField;
            }
            set {
                if ((object.ReferenceEquals(this.strUploadResultField, value) != true)) {
                    this.strUploadResultField = value;
                    this.RaisePropertyChanged("strUploadResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipFileRequest", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class ZipFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPathFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTempFolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strComments {
            get {
                return this.strCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.strCommentsField, value) != true)) {
                    this.strCommentsField = value;
                    this.RaisePropertyChanged("strComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFileName {
            get {
                return this.strFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strFileNameField, value) != true)) {
                    this.strFileNameField = value;
                    this.RaisePropertyChanged("strFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFileType {
            get {
                return this.strFileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.strFileTypeField, value) != true)) {
                    this.strFileTypeField = value;
                    this.RaisePropertyChanged("strFileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPathFile {
            get {
                return this.strPathFileField;
            }
            set {
                if ((object.ReferenceEquals(this.strPathFileField, value) != true)) {
                    this.strPathFileField = value;
                    this.RaisePropertyChanged("strPathFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTempFolder {
            get {
                return this.strTempFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.strTempFolderField, value) != true)) {
                    this.strTempFolderField = value;
                    this.RaisePropertyChanged("strTempFolder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipFileResponse", Namespace="http://schemas.datacontract.org/2004/07/HCMDocuments.CoreBusiness.MessageContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class ZipFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blnIsSuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blnIsSuccessful {
            get {
                return this.blnIsSuccessfulField;
            }
            set {
                if ((this.blnIsSuccessfulField.Equals(value) != true)) {
                    this.blnIsSuccessfulField = value;
                    this.RaisePropertyChanged("blnIsSuccessful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDocumentServices.IwsDocumentHandling")]
    public interface IwsDocumentHandling {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/getFileOnPath", ReplyAction="http://tempuri.org/IwsDocumentHandling/getFileOnPathResponse")]
        BIM.PLD.Website.wsDocumentServices.FileResponse getFileOnPath(BIM.PLD.Website.wsDocumentServices.FileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/setValidatePath", ReplyAction="http://tempuri.org/IwsDocumentHandling/setValidatePathResponse")]
        BIM.PLD.Website.wsDocumentServices.ValidateResponse setValidatePath(BIM.PLD.Website.wsDocumentServices.ValidatePathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/UploadFile", ReplyAction="http://tempuri.org/IwsDocumentHandling/UploadFileResponse")]
        BIM.PLD.Website.wsDocumentServices.UploadFileResponse UploadFile(BIM.PLD.Website.wsDocumentServices.RemoteFileInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/VerifyExistFile", ReplyAction="http://tempuri.org/IwsDocumentHandling/VerifyExistFileResponse")]
        BIM.PLD.Website.wsDocumentServices.ValidateResponse VerifyExistFile(BIM.PLD.Website.wsDocumentServices.FileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/delFileOnPath", ReplyAction="http://tempuri.org/IwsDocumentHandling/delFileOnPathResponse")]
        BIM.PLD.Website.wsDocumentServices.ValidateResponse delFileOnPath(BIM.PLD.Website.wsDocumentServices.FileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/getZipFileOnPath", ReplyAction="http://tempuri.org/IwsDocumentHandling/getZipFileOnPathResponse")]
        BIM.PLD.Website.wsDocumentServices.FileResponse getZipFileOnPath(BIM.PLD.Website.wsDocumentServices.ZipFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentHandling/setArchivosZip", ReplyAction="http://tempuri.org/IwsDocumentHandling/setArchivosZipResponse")]
        BIM.PLD.Website.wsDocumentServices.ZipFileResponse setArchivosZip(BIM.PLD.Website.wsDocumentServices.ZipFileRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsDocumentHandlingChannel : BIM.PLD.Website.wsDocumentServices.IwsDocumentHandling, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsDocumentHandlingClient : System.ServiceModel.ClientBase<BIM.PLD.Website.wsDocumentServices.IwsDocumentHandling>, BIM.PLD.Website.wsDocumentServices.IwsDocumentHandling {
        
        public IwsDocumentHandlingClient() {
        }
        
        public IwsDocumentHandlingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsDocumentHandlingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsDocumentHandlingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsDocumentHandlingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.wsDocumentServices.FileResponse getFileOnPath(BIM.PLD.Website.wsDocumentServices.FileRequest request) {
            return base.Channel.getFileOnPath(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.ValidateResponse setValidatePath(BIM.PLD.Website.wsDocumentServices.ValidatePathRequest request) {
            return base.Channel.setValidatePath(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.UploadFileResponse UploadFile(BIM.PLD.Website.wsDocumentServices.RemoteFileInfoRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.ValidateResponse VerifyExistFile(BIM.PLD.Website.wsDocumentServices.FileRequest request) {
            return base.Channel.VerifyExistFile(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.ValidateResponse delFileOnPath(BIM.PLD.Website.wsDocumentServices.FileRequest request) {
            return base.Channel.delFileOnPath(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.FileResponse getZipFileOnPath(BIM.PLD.Website.wsDocumentServices.ZipFileRequest request) {
            return base.Channel.getZipFileOnPath(request);
        }
        
        public BIM.PLD.Website.wsDocumentServices.ZipFileResponse setArchivosZip(BIM.PLD.Website.wsDocumentServices.ZipFileRequest request) {
            return base.Channel.setArchivosZip(request);
        }
    }
}
