//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.TipoCambioServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCambio", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class TipoCambio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datFechaCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal decValorCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTipoCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTipoMonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datFechaCierre {
            get {
                return this.datFechaCierreField;
            }
            set {
                if ((this.datFechaCierreField.Equals(value) != true)) {
                    this.datFechaCierreField = value;
                    this.RaisePropertyChanged("datFechaCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal decValorCambio {
            get {
                return this.decValorCambioField;
            }
            set {
                if ((this.decValorCambioField.Equals(value) != true)) {
                    this.decValorCambioField = value;
                    this.RaisePropertyChanged("decValorCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoCambio {
            get {
                return this.iTipoCambioField;
            }
            set {
                if ((this.iTipoCambioField.Equals(value) != true)) {
                    this.iTipoCambioField = value;
                    this.RaisePropertyChanged("iTipoCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoMoneda {
            get {
                return this.iTipoMonedaField;
            }
            set {
                if ((this.iTipoMonedaField.Equals(value) != true)) {
                    this.iTipoMonedaField = value;
                    this.RaisePropertyChanged("iTipoMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTipoCambio {
            get {
                return this.strTipoCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.strTipoCambioField, value) != true)) {
                    this.strTipoCambioField = value;
                    this.RaisePropertyChanged("strTipoCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTipoMoneda {
            get {
                return this.strTipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.strTipoMonedaField, value) != true)) {
                    this.strTipoMonedaField = value;
                    this.RaisePropertyChanged("strTipoMoneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoCambioServices.ITipoCambioServices")]
    public interface ITipoCambioServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoCambioServices/getListadoTipoCambio", ReplyAction="http://tempuri.org/ITipoCambioServices/getListadoTipoCambioResponse")]
        BIM.PLD.Website.TipoCambioServices.TipoCambio[] getListadoTipoCambio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoCambioServices/insertaTCManual", ReplyAction="http://tempuri.org/ITipoCambioServices/insertaTCManualResponse")]
        int insertaTCManual(BIM.PLD.Website.TipoCambioServices.TipoCambio modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoCambioServices/insertaTCAutomatico", ReplyAction="http://tempuri.org/ITipoCambioServices/insertaTCAutomaticoResponse")]
        int insertaTCAutomatico(BIM.PLD.Website.TipoCambioServices.TipoCambio[] lst);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITipoCambioServicesChannel : BIM.PLD.Website.TipoCambioServices.ITipoCambioServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioServicesClient : System.ServiceModel.ClientBase<BIM.PLD.Website.TipoCambioServices.ITipoCambioServices>, BIM.PLD.Website.TipoCambioServices.ITipoCambioServices {
        
        public TipoCambioServicesClient() {
        }
        
        public TipoCambioServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.TipoCambioServices.TipoCambio[] getListadoTipoCambio() {
            return base.Channel.getListadoTipoCambio();
        }
        
        public int insertaTCManual(BIM.PLD.Website.TipoCambioServices.TipoCambio modelo) {
            return base.Channel.insertaTCManual(modelo);
        }
        
        public int insertaTCAutomatico(BIM.PLD.Website.TipoCambioServices.TipoCambio[] lst) {
            return base.Channel.insertaTCAutomatico(lst);
        }
    }
}
