//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.BitacoraPLDServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BitacoraPLD", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BitacoraPLD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitAutorizaProcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitHistorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitHomonimoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datFechaRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> intBitacoraIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> intSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> intTipoTipificacionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchApMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchApPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchCorreoHCMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchIdentificadorInternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreBusqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchPersonaIncidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchRelacionClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchTipoListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchUsuarioAuditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchUsuarioNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchidqeqField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalCorreo {
            get {
                return this.TotalCorreoField;
            }
            set {
                if ((this.TotalCorreoField.Equals(value) != true)) {
                    this.TotalCorreoField = value;
                    this.RaisePropertyChanged("TotalCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitAutorizaProc {
            get {
                return this.bitAutorizaProcField;
            }
            set {
                if ((this.bitAutorizaProcField.Equals(value) != true)) {
                    this.bitAutorizaProcField = value;
                    this.RaisePropertyChanged("bitAutorizaProc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitEstatus {
            get {
                return this.bitEstatusField;
            }
            set {
                if ((this.bitEstatusField.Equals(value) != true)) {
                    this.bitEstatusField = value;
                    this.RaisePropertyChanged("bitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitHistorial {
            get {
                return this.bitHistorialField;
            }
            set {
                if ((this.bitHistorialField.Equals(value) != true)) {
                    this.bitHistorialField = value;
                    this.RaisePropertyChanged("bitHistorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitHomonimo {
            get {
                return this.bitHomonimoField;
            }
            set {
                if ((this.bitHomonimoField.Equals(value) != true)) {
                    this.bitHomonimoField = value;
                    this.RaisePropertyChanged("bitHomonimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datFecha {
            get {
                return this.datFechaField;
            }
            set {
                if ((this.datFechaField.Equals(value) != true)) {
                    this.datFechaField = value;
                    this.RaisePropertyChanged("datFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datFechaRespuesta {
            get {
                return this.datFechaRespuestaField;
            }
            set {
                if ((this.datFechaRespuestaField.Equals(value) != true)) {
                    this.datFechaRespuestaField = value;
                    this.RaisePropertyChanged("datFechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> intBitacoraID {
            get {
                return this.intBitacoraIDField;
            }
            set {
                if ((this.intBitacoraIDField.Equals(value) != true)) {
                    this.intBitacoraIDField = value;
                    this.RaisePropertyChanged("intBitacoraID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> intSistema {
            get {
                return this.intSistemaField;
            }
            set {
                if ((this.intSistemaField.Equals(value) != true)) {
                    this.intSistemaField = value;
                    this.RaisePropertyChanged("intSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> intTipoTipificacionID {
            get {
                return this.intTipoTipificacionIDField;
            }
            set {
                if ((this.intTipoTipificacionIDField.Equals(value) != true)) {
                    this.intTipoTipificacionIDField = value;
                    this.RaisePropertyChanged("intTipoTipificacionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchApMaterno {
            get {
                return this.vchApMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchApMaternoField, value) != true)) {
                    this.vchApMaternoField = value;
                    this.RaisePropertyChanged("vchApMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchApPaterno {
            get {
                return this.vchApPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchApPaternoField, value) != true)) {
                    this.vchApPaternoField = value;
                    this.RaisePropertyChanged("vchApPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCliente {
            get {
                return this.vchClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.vchClienteField, value) != true)) {
                    this.vchClienteField = value;
                    this.RaisePropertyChanged("vchCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchComentario {
            get {
                return this.vchComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchComentarioField, value) != true)) {
                    this.vchComentarioField = value;
                    this.RaisePropertyChanged("vchComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCorreoHCM {
            get {
                return this.vchCorreoHCMField;
            }
            set {
                if ((object.ReferenceEquals(this.vchCorreoHCMField, value) != true)) {
                    this.vchCorreoHCMField = value;
                    this.RaisePropertyChanged("vchCorreoHCM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchIdentificadorInterno {
            get {
                return this.vchIdentificadorInternoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchIdentificadorInternoField, value) != true)) {
                    this.vchIdentificadorInternoField = value;
                    this.RaisePropertyChanged("vchIdentificadorInterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombre {
            get {
                return this.vchNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreField, value) != true)) {
                    this.vchNombreField = value;
                    this.RaisePropertyChanged("vchNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombreBusq {
            get {
                return this.vchNombreBusqField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreBusqField, value) != true)) {
                    this.vchNombreBusqField = value;
                    this.RaisePropertyChanged("vchNombreBusq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombreCompleto {
            get {
                return this.vchNombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreCompletoField, value) != true)) {
                    this.vchNombreCompletoField = value;
                    this.RaisePropertyChanged("vchNombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombreSistema {
            get {
                return this.vchNombreSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreSistemaField, value) != true)) {
                    this.vchNombreSistemaField = value;
                    this.RaisePropertyChanged("vchNombreSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchPersonaIncidencia {
            get {
                return this.vchPersonaIncidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.vchPersonaIncidenciaField, value) != true)) {
                    this.vchPersonaIncidenciaField = value;
                    this.RaisePropertyChanged("vchPersonaIncidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchRelacionCliente {
            get {
                return this.vchRelacionClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.vchRelacionClienteField, value) != true)) {
                    this.vchRelacionClienteField = value;
                    this.RaisePropertyChanged("vchRelacionCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchSucursal {
            get {
                return this.vchSucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.vchSucursalField, value) != true)) {
                    this.vchSucursalField = value;
                    this.RaisePropertyChanged("vchSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchTipoLista {
            get {
                return this.vchTipoListaField;
            }
            set {
                if ((object.ReferenceEquals(this.vchTipoListaField, value) != true)) {
                    this.vchTipoListaField = value;
                    this.RaisePropertyChanged("vchTipoLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchUsuario {
            get {
                return this.vchUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchUsuarioField, value) != true)) {
                    this.vchUsuarioField = value;
                    this.RaisePropertyChanged("vchUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchUsuarioAudit {
            get {
                return this.vchUsuarioAuditField;
            }
            set {
                if ((object.ReferenceEquals(this.vchUsuarioAuditField, value) != true)) {
                    this.vchUsuarioAuditField = value;
                    this.RaisePropertyChanged("vchUsuarioAudit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchUsuarioNombre {
            get {
                return this.vchUsuarioNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vchUsuarioNombreField, value) != true)) {
                    this.vchUsuarioNombreField = value;
                    this.RaisePropertyChanged("vchUsuarioNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchidqeq {
            get {
                return this.vchidqeqField;
            }
            set {
                if ((object.ReferenceEquals(this.vchidqeqField, value) != true)) {
                    this.vchidqeqField = value;
                    this.RaisePropertyChanged("vchidqeq");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD[]))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceOk {
            get {
                return this.ServiceOkField;
            }
            set {
                if ((this.ServiceOkField.Equals(value) != true)) {
                    this.ServiceOkField = value;
                    this.RaisePropertyChanged("ServiceOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BitacoraPLDServices.IBitacoraPLDServices")]
    public interface IBitacoraPLDServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraPLDServices/ListadoBusquedaBitacoraPLD", ReplyAction="http://tempuri.org/IBitacoraPLDServices/ListadoBusquedaBitacoraPLDResponse")]
        BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD[] ListadoBusquedaBitacoraPLD(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD bitacora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraPLDServices/desbloquearUsuario", ReplyAction="http://tempuri.org/IBitacoraPLDServices/desbloquearUsuarioResponse")]
        BIM.PLD.Website.BitacoraPLDServices.ServiceResult desbloquearUsuario(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraPLDServices/editarBitacoraPLD", ReplyAction="http://tempuri.org/IBitacoraPLDServices/editarBitacoraPLDResponse")]
        BIM.PLD.Website.BitacoraPLDServices.ServiceResult editarBitacoraPLD(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD parametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBitacoraPLDServicesChannel : BIM.PLD.Website.BitacoraPLDServices.IBitacoraPLDServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BitacoraPLDServicesClient : System.ServiceModel.ClientBase<BIM.PLD.Website.BitacoraPLDServices.IBitacoraPLDServices>, BIM.PLD.Website.BitacoraPLDServices.IBitacoraPLDServices {
        
        public BitacoraPLDServicesClient() {
        }
        
        public BitacoraPLDServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BitacoraPLDServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraPLDServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraPLDServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD[] ListadoBusquedaBitacoraPLD(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD bitacora) {
            return base.Channel.ListadoBusquedaBitacoraPLD(bitacora);
        }
        
        public BIM.PLD.Website.BitacoraPLDServices.ServiceResult desbloquearUsuario(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD parametros) {
            return base.Channel.desbloquearUsuario(parametros);
        }
        
        public BIM.PLD.Website.BitacoraPLDServices.ServiceResult editarBitacoraPLD(BIM.PLD.Website.BitacoraPLDServices.BitacoraPLD parametros) {
            return base.Channel.editarBitacoraPLD(parametros);
        }
    }
}
