#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLDWS.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPLD")]
	public partial class ConfiguracionPLDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConfiguracionPLDDataContext() : 
				base(global::BIM.PLDWS.DataAccess.Properties.Settings.Default.PLDConexionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionPLDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionPLDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionPLDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionPLDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_CRUDConfiguracionPLD")]
		public ISingleResult<stp_CRUDConfiguracionPLDResult> stp_CRUDConfiguracionPLD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intAccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoTipificacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sintSistemaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitBloqueoUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitBloqueoProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitEnvioCorreo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitBitacora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchMensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchCorreosPara, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchCorreosCC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, intAccion, intTipoTipificacionID, sintSistemaID, bitBloqueoUsuario, bitBloqueoProceso, bitEnvioCorreo, bitBitacora, vchMensaje, vchCorreosPara, vchCorreosCC);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_CRUDConfiguracionPLDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class stp_CRUDConfiguracionPLDResult
	{
		
		private int _intTipoTipificacionID;
		
		private string _vchIdentificadorInterno;
		
		private short _sintSistemaID;
		
		private string _vchNombreSistema;
		
		private string _vchbitBloqueoUsuario;
		
		private System.Nullable<bool> _bitBloqueoUsuario;
		
		private string _vchbitBloqueProceso;
		
		private System.Nullable<bool> _bitBloqueoProceso;
		
		private string _vchbitEnvioCorreo;
		
		private System.Nullable<bool> _bitEnvioCorreo;
		
		private string _vchbitBitacora;
		
		private System.Nullable<bool> _bitBitacora;
		
		private string _vchMensaje;
		
		private string _vchCorreosPara;
		
		private string _vchCorreosCC;
		
		public stp_CRUDConfiguracionPLDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoTipificacionID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int intTipoTipificacionID
		{
			get
			{
				return this._intTipoTipificacionID;
			}
			set
			{
				if ((this._intTipoTipificacionID != value))
				{
					this._intTipoTipificacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchIdentificadorInterno", DbType="VarChar(25)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string vchIdentificadorInterno
		{
			get
			{
				return this._vchIdentificadorInterno;
			}
			set
			{
				if ((this._vchIdentificadorInterno != value))
				{
					this._vchIdentificadorInterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintSistemaID", DbType="SmallInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public short sintSistemaID
		{
			get
			{
				return this._sintSistemaID;
			}
			set
			{
				if ((this._sintSistemaID != value))
				{
					this._sintSistemaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombreSistema", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string vchNombreSistema
		{
			get
			{
				return this._vchNombreSistema;
			}
			set
			{
				if ((this._vchNombreSistema != value))
				{
					this._vchNombreSistema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchbitBloqueoUsuario", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string vchbitBloqueoUsuario
		{
			get
			{
				return this._vchbitBloqueoUsuario;
			}
			set
			{
				if ((this._vchbitBloqueoUsuario != value))
				{
					this._vchbitBloqueoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitBloqueoUsuario", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<bool> bitBloqueoUsuario
		{
			get
			{
				return this._bitBloqueoUsuario;
			}
			set
			{
				if ((this._bitBloqueoUsuario != value))
				{
					this._bitBloqueoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchbitBloqueProceso", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string vchbitBloqueProceso
		{
			get
			{
				return this._vchbitBloqueProceso;
			}
			set
			{
				if ((this._vchbitBloqueProceso != value))
				{
					this._vchbitBloqueProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitBloqueoProceso", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<bool> bitBloqueoProceso
		{
			get
			{
				return this._bitBloqueoProceso;
			}
			set
			{
				if ((this._bitBloqueoProceso != value))
				{
					this._bitBloqueoProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchbitEnvioCorreo", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string vchbitEnvioCorreo
		{
			get
			{
				return this._vchbitEnvioCorreo;
			}
			set
			{
				if ((this._vchbitEnvioCorreo != value))
				{
					this._vchbitEnvioCorreo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitEnvioCorreo", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<bool> bitEnvioCorreo
		{
			get
			{
				return this._bitEnvioCorreo;
			}
			set
			{
				if ((this._bitEnvioCorreo != value))
				{
					this._bitEnvioCorreo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchbitBitacora", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string vchbitBitacora
		{
			get
			{
				return this._vchbitBitacora;
			}
			set
			{
				if ((this._vchbitBitacora != value))
				{
					this._vchbitBitacora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitBitacora", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<bool> bitBitacora
		{
			get
			{
				return this._bitBitacora;
			}
			set
			{
				if ((this._bitBitacora != value))
				{
					this._bitBitacora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMensaje", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string vchMensaje
		{
			get
			{
				return this._vchMensaje;
			}
			set
			{
				if ((this._vchMensaje != value))
				{
					this._vchMensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCorreosPara", DbType="VarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string vchCorreosPara
		{
			get
			{
				return this._vchCorreosPara;
			}
			set
			{
				if ((this._vchCorreosPara != value))
				{
					this._vchCorreosPara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCorreosCC", DbType="VarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string vchCorreosCC
		{
			get
			{
				return this._vchCorreosCC;
			}
			set
			{
				if ((this._vchCorreosCC != value))
				{
					this._vchCorreosCC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
