#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPLD")]
	public partial class CatalogosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public CatalogosDataContext() : 
				base(global::BIM.PLD.DataAccess.Properties.Settings.Default.dbPLDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CatalogosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CatalogosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CatalogosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CatalogosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatAccionesPLD")]
		public ISingleResult<stp_ListarCatAccionesPLDResult> stp_ListarCatAccionesPLD()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarCatAccionesPLDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatTipoListaNegra")]
		public ISingleResult<stp_ListarCatTipoListaNegraResult> stp_ListarCatTipoListaNegra()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarCatTipoListaNegraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatTipoLista")]
		public ISingleResult<stp_ListarCatTipoListaResult> stp_ListarCatTipoLista()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarCatTipoListaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_BusquedaInteligenteTipoTipificacion")]
		public ISingleResult<stp_BusquedaInteligenteTipoTipificacionResult> stp_BusquedaInteligenteTipoTipificacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cadena", DbType="VarChar(2000)")] string cadena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cadena);
			return ((ISingleResult<stp_BusquedaInteligenteTipoTipificacionResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarCatAccionesPLDResult
	{
		
		private int _INTACCIONPLDID;
		
		private string _VCHDESCRIPCION;
		
		private System.Nullable<bool> _BITESTATUS;
		
		public stp_ListarCatAccionesPLDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTACCIONPLDID", DbType="Int NOT NULL")]
		public int INTACCIONPLDID
		{
			get
			{
				return this._INTACCIONPLDID;
			}
			set
			{
				if ((this._INTACCIONPLDID != value))
				{
					this._INTACCIONPLDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCHDESCRIPCION", DbType="VarChar(256)")]
		public string VCHDESCRIPCION
		{
			get
			{
				return this._VCHDESCRIPCION;
			}
			set
			{
				if ((this._VCHDESCRIPCION != value))
				{
					this._VCHDESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BITESTATUS", DbType="Bit")]
		public System.Nullable<bool> BITESTATUS
		{
			get
			{
				return this._BITESTATUS;
			}
			set
			{
				if ((this._BITESTATUS != value))
				{
					this._BITESTATUS = value;
				}
			}
		}
	}
	
	public partial class stp_ListarCatTipoListaNegraResult
	{
		
		private int _intTipoTipificacionID;
		
		private string _vchDescripcion;
		
		public stp_ListarCatTipoListaNegraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoTipificacionID", DbType="Int NOT NULL")]
		public int intTipoTipificacionID
		{
			get
			{
				return this._intTipoTipificacionID;
			}
			set
			{
				if ((this._intTipoTipificacionID != value))
				{
					this._intTipoTipificacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(25)")]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_ListarCatTipoListaResult
	{
		
		private string _vchTipoLista;
		
		private int _intTipoListaID;
		
		public stp_ListarCatTipoListaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoLista", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string vchTipoLista
		{
			get
			{
				return this._vchTipoLista;
			}
			set
			{
				if ((this._vchTipoLista != value))
				{
					this._vchTipoLista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoListaID", DbType="Int NOT NULL")]
		public int intTipoListaID
		{
			get
			{
				return this._intTipoListaID;
			}
			set
			{
				if ((this._intTipoListaID != value))
				{
					this._intTipoListaID = value;
				}
			}
		}
	}
	
	public partial class stp_BusquedaInteligenteTipoTipificacionResult
	{
		
		private int _intTipoTipificacionID;
		
		private string _vchDescripcion;
		
		public stp_BusquedaInteligenteTipoTipificacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoTipificacionID", DbType="Int NOT NULL")]
		public int intTipoTipificacionID
		{
			get
			{
				return this._intTipoTipificacionID;
			}
			set
			{
				if ((this._intTipoTipificacionID != value))
				{
					this._intTipoTipificacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(25)")]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
