#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLDWS.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbCatalogosGrales")]
	public partial class WSCarolineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public WSCarolineDataContext() : 
				base(global::BIM.PLDWS.DataAccess.Properties.Settings.Default.PLDConexionString, mappingSource)
		{
			OnCreated();
		}
		
		public WSCarolineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSCarolineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSCarolineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSCarolineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCaroline")]
		public ISingleResult<stp_ListarCarolineResult> stp_ListarCaroline()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarCarolineResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_InsertarCaroline")]
		public int stp_InsertarCaroline([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intWSCarolineID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoTipificacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intClienteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCalificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intWSCarolineID, intTipoTipificacionID, intClienteID, intPersonaID, intCalificacion);
			intWSCarolineID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class stp_ListarCarolineResult
	{
		
		private int _intWSCarolineID;
		
		private System.Nullable<int> _intTipoPersonaID;
		
		private System.Nullable<int> _intClienteID;
		
		private string _vchTipificacion;
		
		private System.Nullable<int> _intCalificacion;
		
		private System.Nullable<System.DateTime> _datFecha;
		
		private System.Nullable<bool> _bitEstatus;
		
		public stp_ListarCarolineResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWSCarolineID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int intWSCarolineID
		{
			get
			{
				return this._intWSCarolineID;
			}
			set
			{
				if ((this._intWSCarolineID != value))
				{
					this._intWSCarolineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoPersonaID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> intTipoPersonaID
		{
			get
			{
				return this._intTipoPersonaID;
			}
			set
			{
				if ((this._intTipoPersonaID != value))
				{
					this._intTipoPersonaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intClienteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> intClienteID
		{
			get
			{
				return this._intClienteID;
			}
			set
			{
				if ((this._intClienteID != value))
				{
					this._intClienteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipificacion", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string vchTipificacion
		{
			get
			{
				return this._vchTipificacion;
			}
			set
			{
				if ((this._vchTipificacion != value))
				{
					this._vchTipificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCalificacion", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> intCalificacion
		{
			get
			{
				return this._intCalificacion;
			}
			set
			{
				if ((this._intCalificacion != value))
				{
					this._intCalificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFecha", DbType="Date")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> datFecha
		{
			get
			{
				return this._datFecha;
			}
			set
			{
				if ((this._datFecha != value))
				{
					this._datFecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitEstatus", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<bool> bitEstatus
		{
			get
			{
				return this._bitEstatus;
			}
			set
			{
				if ((this._bitEstatus != value))
				{
					this._bitEstatus = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
