//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.wsFovissste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://avaluoswebservice.fovissste.com.mx/", ConfigurationName="wsFovissste.RecibeAvaluosWebServiceSoap")]
    public interface RecibeAvaluosWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://avaluoswebservice.fovissste.com.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://avaluoswebservice.fovissste.com.mx/RecibirAvaluos", ReplyAction="*")]
        BIM.PLD.Website.wsFovissste.RecibirAvaluosResponse RecibirAvaluos(BIM.PLD.Website.wsFovissste.RecibirAvaluosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirAvaluosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibirAvaluos", Namespace="http://avaluoswebservice.fovissste.com.mx/", Order=0)]
        public BIM.PLD.Website.wsFovissste.RecibirAvaluosRequestBody Body;
        
        public RecibirAvaluosRequest() {
        }
        
        public RecibirAvaluosRequest(BIM.PLD.Website.wsFovissste.RecibirAvaluosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://avaluoswebservice.fovissste.com.mx/")]
    public partial class RecibirAvaluosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cuv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml;
        
        public RecibirAvaluosRequestBody() {
        }
        
        public RecibirAvaluosRequestBody(string usuario, string password, string cuv, string xml) {
            this.usuario = usuario;
            this.password = password;
            this.cuv = cuv;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirAvaluosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibirAvaluosResponse", Namespace="http://avaluoswebservice.fovissste.com.mx/", Order=0)]
        public BIM.PLD.Website.wsFovissste.RecibirAvaluosResponseBody Body;
        
        public RecibirAvaluosResponse() {
        }
        
        public RecibirAvaluosResponse(BIM.PLD.Website.wsFovissste.RecibirAvaluosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://avaluoswebservice.fovissste.com.mx/")]
    public partial class RecibirAvaluosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecibirAvaluosResult;
        
        public RecibirAvaluosResponseBody() {
        }
        
        public RecibirAvaluosResponseBody(string RecibirAvaluosResult) {
            this.RecibirAvaluosResult = RecibirAvaluosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecibeAvaluosWebServiceSoapChannel : BIM.PLD.Website.wsFovissste.RecibeAvaluosWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecibeAvaluosWebServiceSoapClient : System.ServiceModel.ClientBase<BIM.PLD.Website.wsFovissste.RecibeAvaluosWebServiceSoap>, BIM.PLD.Website.wsFovissste.RecibeAvaluosWebServiceSoap {
        
        public RecibeAvaluosWebServiceSoapClient() {
        }
        
        public RecibeAvaluosWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecibeAvaluosWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecibeAvaluosWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecibeAvaluosWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIM.PLD.Website.wsFovissste.RecibirAvaluosResponse BIM.PLD.Website.wsFovissste.RecibeAvaluosWebServiceSoap.RecibirAvaluos(BIM.PLD.Website.wsFovissste.RecibirAvaluosRequest request) {
            return base.Channel.RecibirAvaluos(request);
        }
        
        public string RecibirAvaluos(string usuario, string password, string cuv, string xml) {
            BIM.PLD.Website.wsFovissste.RecibirAvaluosRequest inValue = new BIM.PLD.Website.wsFovissste.RecibirAvaluosRequest();
            inValue.Body = new BIM.PLD.Website.wsFovissste.RecibirAvaluosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.cuv = cuv;
            inValue.Body.xml = xml;
            BIM.PLD.Website.wsFovissste.RecibirAvaluosResponse retVal = ((BIM.PLD.Website.wsFovissste.RecibeAvaluosWebServiceSoap)(this)).RecibirAvaluos(inValue);
            return retVal.Body.RecibirAvaluosResult;
        }
    }
}
