//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.ConfiguracionPLDServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfiguracionPLD", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class ConfiguracionPLD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitBitacoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitBloqueoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitBloqueoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitEnvioCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> intTipoTipificacionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> sintSistemaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchCorreosCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchCorreosParaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchIdentificadorInternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchNombreSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchbitBitacoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchbitBloqueoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchbitBloqueoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchbitEnvioCorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitBitacora {
            get {
                return this.bitBitacoraField;
            }
            set {
                if ((this.bitBitacoraField.Equals(value) != true)) {
                    this.bitBitacoraField = value;
                    this.RaisePropertyChanged("bitBitacora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitBloqueoProceso {
            get {
                return this.bitBloqueoProcesoField;
            }
            set {
                if ((this.bitBloqueoProcesoField.Equals(value) != true)) {
                    this.bitBloqueoProcesoField = value;
                    this.RaisePropertyChanged("bitBloqueoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitBloqueoUsuario {
            get {
                return this.bitBloqueoUsuarioField;
            }
            set {
                if ((this.bitBloqueoUsuarioField.Equals(value) != true)) {
                    this.bitBloqueoUsuarioField = value;
                    this.RaisePropertyChanged("bitBloqueoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitEnvioCorreo {
            get {
                return this.bitEnvioCorreoField;
            }
            set {
                if ((this.bitEnvioCorreoField.Equals(value) != true)) {
                    this.bitEnvioCorreoField = value;
                    this.RaisePropertyChanged("bitEnvioCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> intTipoTipificacionID {
            get {
                return this.intTipoTipificacionIDField;
            }
            set {
                if ((this.intTipoTipificacionIDField.Equals(value) != true)) {
                    this.intTipoTipificacionIDField = value;
                    this.RaisePropertyChanged("intTipoTipificacionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> sintSistemaID {
            get {
                return this.sintSistemaIDField;
            }
            set {
                if ((this.sintSistemaIDField.Equals(value) != true)) {
                    this.sintSistemaIDField = value;
                    this.RaisePropertyChanged("sintSistemaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCorreosCC {
            get {
                return this.vchCorreosCCField;
            }
            set {
                if ((object.ReferenceEquals(this.vchCorreosCCField, value) != true)) {
                    this.vchCorreosCCField = value;
                    this.RaisePropertyChanged("vchCorreosCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchCorreosPara {
            get {
                return this.vchCorreosParaField;
            }
            set {
                if ((object.ReferenceEquals(this.vchCorreosParaField, value) != true)) {
                    this.vchCorreosParaField = value;
                    this.RaisePropertyChanged("vchCorreosPara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchIdentificadorInterno {
            get {
                return this.vchIdentificadorInternoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchIdentificadorInternoField, value) != true)) {
                    this.vchIdentificadorInternoField = value;
                    this.RaisePropertyChanged("vchIdentificadorInterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchMensaje {
            get {
                return this.vchMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.vchMensajeField, value) != true)) {
                    this.vchMensajeField = value;
                    this.RaisePropertyChanged("vchMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchNombreSistema {
            get {
                return this.vchNombreSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.vchNombreSistemaField, value) != true)) {
                    this.vchNombreSistemaField = value;
                    this.RaisePropertyChanged("vchNombreSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchbitBitacora {
            get {
                return this.vchbitBitacoraField;
            }
            set {
                if ((object.ReferenceEquals(this.vchbitBitacoraField, value) != true)) {
                    this.vchbitBitacoraField = value;
                    this.RaisePropertyChanged("vchbitBitacora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchbitBloqueoProceso {
            get {
                return this.vchbitBloqueoProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchbitBloqueoProcesoField, value) != true)) {
                    this.vchbitBloqueoProcesoField = value;
                    this.RaisePropertyChanged("vchbitBloqueoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchbitBloqueoUsuario {
            get {
                return this.vchbitBloqueoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchbitBloqueoUsuarioField, value) != true)) {
                    this.vchbitBloqueoUsuarioField = value;
                    this.RaisePropertyChanged("vchbitBloqueoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchbitEnvioCorreo {
            get {
                return this.vchbitEnvioCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.vchbitEnvioCorreoField, value) != true)) {
                    this.vchbitEnvioCorreoField = value;
                    this.RaisePropertyChanged("vchbitEnvioCorreo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD[]))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceOk {
            get {
                return this.ServiceOkField;
            }
            set {
                if ((this.ServiceOkField.Equals(value) != true)) {
                    this.ServiceOkField = value;
                    this.RaisePropertyChanged("ServiceOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfiguracionPLDServices.IConfiguracionPLDServices")]
    public interface IConfiguracionPLDServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionPLDServices/InsertarConfiguracionPLD", ReplyAction="http://tempuri.org/IConfiguracionPLDServices/InsertarConfiguracionPLDResponse")]
        BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult InsertarConfiguracionPLD(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD oConfiguracionPLD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionPLDServices/ListadoBusquedaConfiguracionPLD", ReplyAction="http://tempuri.org/IConfiguracionPLDServices/ListadoBusquedaConfiguracionPLDRespo" +
            "nse")]
        BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD[] ListadoBusquedaConfiguracionPLD(System.Nullable<int> intTipoTipificacionID, System.Nullable<short> sintSistemaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionPLDServices/editarConfiguracionPLD", ReplyAction="http://tempuri.org/IConfiguracionPLDServices/editarConfiguracionPLDResponse")]
        BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult editarConfiguracionPLD(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD _datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionPLDServices/eliminarConfiguracionPLD", ReplyAction="http://tempuri.org/IConfiguracionPLDServices/eliminarConfiguracionPLDResponse")]
        BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult eliminarConfiguracionPLD(System.Nullable<int> intTipoTipificacionID, System.Nullable<short> sintSistemaID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfiguracionPLDServicesChannel : BIM.PLD.Website.ConfiguracionPLDServices.IConfiguracionPLDServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfiguracionPLDServicesClient : System.ServiceModel.ClientBase<BIM.PLD.Website.ConfiguracionPLDServices.IConfiguracionPLDServices>, BIM.PLD.Website.ConfiguracionPLDServices.IConfiguracionPLDServices {
        
        public ConfiguracionPLDServicesClient() {
        }
        
        public ConfiguracionPLDServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfiguracionPLDServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfiguracionPLDServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfiguracionPLDServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult InsertarConfiguracionPLD(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD oConfiguracionPLD) {
            return base.Channel.InsertarConfiguracionPLD(oConfiguracionPLD);
        }
        
        public BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD[] ListadoBusquedaConfiguracionPLD(System.Nullable<int> intTipoTipificacionID, System.Nullable<short> sintSistemaID) {
            return base.Channel.ListadoBusquedaConfiguracionPLD(intTipoTipificacionID, sintSistemaID);
        }
        
        public BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult editarConfiguracionPLD(BIM.PLD.Website.ConfiguracionPLDServices.ConfiguracionPLD _datos) {
            return base.Channel.editarConfiguracionPLD(_datos);
        }
        
        public BIM.PLD.Website.ConfiguracionPLDServices.ServiceResult eliminarConfiguracionPLD(System.Nullable<int> intTipoTipificacionID, System.Nullable<short> sintSistemaID) {
            return base.Channel.eliminarConfiguracionPLD(intTipoTipificacionID, sintSistemaID);
        }
    }
}
