SELECT * FROM CLPUESTO
ALTER TABLE CLPUESTO ADD Rel_SIHCEI VARCHAR(10) NULL

INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('027','DUEÑO','','','','','','','1')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('028','DIRECTOR','','','','','','','2')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('029','SUBDIRECTOR','','','','','','','3')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('030','GERENTE','','','','','','','4')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('031','SUBGERENTE','','','','','','','5')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('032','SUPERVISOR','','','','','','','6')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('033','COORDINADOR','','','','','','','7')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('034','AUXILIAR','','','','','','','8')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('035','AYUDANTE','','','','','','','9')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('036','ANALISTA','','','','','','','10')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('037','ASISTENTE','','','','','','','11')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('038','OPERADOR','','','','','','','12')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('039','ENCARGADO','','','','','','','13')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('040','JEFE','','','','','','','14')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('041','PENSIONADO','','','','','','','15')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('042','MILITAR','','','','','','','16')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('043','OBRERO','','','','','','','17')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('044','OTRO','','','','','','','18')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('045','PRESIDENTE','','','','','','','19')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('046','DIRECTOR DE OBRA','','','','','','','20')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('047','DIRECTOR HIPOTECARIO','','','','','','','21')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('048','DIRECTOR ADMINISTRATIVO','','','','','','','22')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('049','DIRECTOR GENERAL','','','','','','','23')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('050','ADMINISTRADOR UNICO','','','','','','','24')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('051','GERENTE GENERAL','','','','','','','25')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('052','GERENTE DE ADMINISTRACION','','','','','','','26')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('053','GERENTE DE COMERCIALIZACION','','','','','','','27')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('054','GERENTE DE CONSTRUCCION','','','','','','','28')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('055','GERENTE DE PROYECTOS','','','','','','','29')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('056','PRINCIPAL ACCIONISTA','','','','','','','30')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('057','GERENTE DE FINANZAS','','','','','','','31')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('058','DIRECTOR DE OPERACIONES','','','','','','','32')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('059','REPRESENTANTE LEGAL','','','','','','','33')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('060','DIRECTOR DE CONTABILIDAD','','','','','','','34')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('061','DIRECTOR COMERCIAL','','','','','','','35')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('062','DIRECTOR DE PROYECTOS','','','','','','','36')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('063','DIRECCION DE PLANEACION Y PROYECTOS','','','','','','','37')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('064','GERENTE CONSTRUCCION','','','','','','','38')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('065','GERENTE COSTOS','','','','','','','39')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('066','PRESIDENTE DEL CONSEJO','','','','','','','40')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('067','DIRECTOR DE COMPRAS','','','','','','','41')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('068','ADMINISTRADOR','','','','','','','42')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('069','DIRECTOR DE CONSTRUCCION','','','','','','','43')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('070','TESORERO','','','','','','','44')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('071','VICEPRESIDENTE','','','','','','','45')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('072','DIRECTOR DE ADMINISTRACION Y FINANZAS','','','','','','','46')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('073','DIRECTOR JURIDICO','','','','','','','47')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('074','DIRECTOR DE FINANZAS','','','','','','','48')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('075','GERENTE DE INDIVIDUALIZACION','','','','','','','49')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('076','PROMOCION DE VIVIENDA','','','','','','','50')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('077','PRESIDENTE CONSEJO ADM.','','','','','','','51')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('078','CONTRALORIA','','','','','','','52')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('079','PRESIDENTE HONORARIO','','','','','','','53')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('080','DIRECTOR DEL CONSEJO','','','','','','','54')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('081','CONTRALOR','','','','','','','55')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('082','PROFESOR NORMALISTA','','','','','','','56')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('083','ACTUARIO JUDICIAL','','','','','','','57')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('084','ADMINISTRADOR GENERAL','','','','','','','58')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('085','LIDER DE PROYECTO','','','','','','','59')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('086','GERENTE CREDITO PUENTE','','','','','','','60')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('087','GESTORIA Y ADMINISTRACION','','','','','','','61')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('088','RESPONSABLE DE OBRA','','','','','','','62')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('089','COMITE DE DIRECCION','','','','','','','63')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('090','DIRECTOR COMERCIAL NUTRICIONAL','','','','','','','64')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('091','DIRECTOR DE PLANEACION','','','','','','','65')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('092','JEFE RECURSOS HUMANOS','','','','','','','66')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('093','DIRECTOR AREA TECNICA','','','','','','','67')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('094','ENFERMERA GENERAL','','','','','','','68')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('095','SECRETARIO DE TRIBUNAL','','','','','','','69')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('096','GERENTE DE RECURSOS HUMANOS','','','','','','','70')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('097','JEFE DE MANTENIMIENTO','','','','','','','71')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('098','MEDICO','','','','','','','72')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('099','TECNICO MECANICO DE TRANSMISIONES','','','','','','','73')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('100','JEFE DE ADMINISTRACION DE VENTAS','','','','','','','74')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('101','GERENTE DE ADMINISTRACION Y VENTAS','','','','','','','75')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('102','AUXILIAR DE JEFE','','','','','','','76')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('103','DOCENTE','','','','','','','77')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('104','AGENTE DE VENTAS','','','','','','','78')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('105','COORDINADOR DE TRAFICO','','','','','','','79')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('106','GERENTE ADMINISTRATIVO','','','','','','','80')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('107','GERENTE DE MARKETING Y NEGOCIOS ','','','','','','','81')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('108','SECRETARIO','','','','','','','82')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('109','DIRECTOR DE CONTRUCCION','','','','','','','83')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('110','CAJERO','','','','','','','84')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('111','LIDER COMISIONISTA','','','','','','','85')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('112','CONTADOR','','','','','','','86')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('113','INGENIERO INDUSTRIAL','','','','','','','87')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('114','DIRECTOR ESTRATEGIA Y FINANZAS','','','','','','','88')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('115','GERENTE DE CREDITOS PUENTE','','','','','','','89')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('116','COMITE DIRECTIVO','','','','','','','90')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('117','DIRECTOR GENERAL Y SOCIO','','','','','','','91')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('118','ALBAÑIL','','','','','','','92')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('119','GERENTE DE CREDITO Y COBRANZAS','','','','','','','93')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('120','MAESTRA JUBILADA','','','','','','','94')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('121','EJECUTIVO DE DESARROLLO','','','','','','','95')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('122','AUXILIAR ADMINSTRATIVO','','','','','','','96')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('123','ABOGADO','','','','','','','97')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('124','CAJERA','','','','','','','98')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('125','COORDINADOR DE VIVIENDA','','','','','','','99')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('126','CONTADOR GENERAL','','','','','','','100')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('127','DIRECTOR TECNICO','','','','','','','101')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('128','SUBDIRECTOR FINANCIERO','','','','','','','102')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('129','CAMILLERO','','','','','','','103')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('130','COMPRADOR MRO','','','','','','','104')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('131','ASISTENTE DE SERVICIOS EN EL PLANTEL','','','','','','','105')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('132','DIRECTOR FINANZAS','','','','','','','106')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('133','JEFE DE PLANTA','','','','','','','107')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('134','MEDICO GENERAL A','','','','','','','108')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('135','MAESTRA PRIMARIA','','','','','','','109')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('136','SECRETARIA TECNICA DE FONDO DE APORTACION DE SEGURIDAD PUBLICA','','','','','','','110')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('137','EJECUTIVO DE VENTAS','','','','','','','111')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('138','TRABAJADOR SOCIAL','','','','','','','112')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('139','EMPLEADO DE MANTENIMIENTO','','','','','','','113')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('140','CAMARISTA','','','','','','','114')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('141','MESERO','','','','','','','115')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('142','MAESTRO DE GRUPO PRIMARIA','','','','','','','116')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('143','CANTINERO','','','','','','','117')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('144','APODERADO','','','','','','','118')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('145','CATEGORIA DE INVESTIGADOR','','','','','','','119')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('146','REDACCION','','','','','','','120')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('147','GERENTE DE VENTAS','','','','','','','121')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('148','INSTALADOR DE TODLDOS DE LONA','','','','','','','122')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('149','SECRETARIO DE CONSEJO','','','','','','','123')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('150','INSPECTOR DE OBRA','','','','','','','124')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('151','JUBILADO','','','','','','','125')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('152','DIRECTOR DE GESTORIA','','','','','','','126')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('153','DIRECTOR DE EDIFICACION','','','','','','','127')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('154','FISCALISTA','','','','','','','128')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('155','SECRETARIA','','','','','','','129')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('156','MAESTRO DE GRUPO','','','','','','','130')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('157','EMBARQUES','','','','','','','131')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('158','DIRECTOR DE VIVIENDA','','','','','','','132')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('159','BARTENDER','','','','','','','133')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('160','PROPIETARIO','','','','','','','134')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('161','SUBOFICIAL','','','','','','','135')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('162','MONITOR CONTENIDO ON LINE','','','','','','','136')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('163','PROFESIONISTA ESPECIALISTA "C"','','','','','','','137')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('164','POLICIA','','','','','','','138')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('165','PROFESOR DE CARRERA','','','','','','','139')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('166','RESPONSABLE DE SOPORTE TECNICO','','','','','','','140')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('167','ROTULISTA','','','','','','','141')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('168','VENDEDOR','','','','','','','142')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('169','SECRETARIO ACTUARIO','','','','','','','143')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('170','INGENIERO MECATRONICO','','','','','','','144')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('171','GERENTE COMERCIAL','','','','','','','145')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('172','ESPECIALISTA TECNICO "C" NIVEL 35','','','','','','','146')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('173','GERENTE DE DISEÑO','','','','','','','147')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('174','JEFE DE ESTADISTICA Y ARCHIVO','','','','','','','148')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('175','PROFESORA DE ASIGNATURA C','','','','','','','149')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('176','SECRETARIA DE ACUERDOS DE JUZGADO DE PAZ','','','','','','','150')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('177','SUB´DIRECTOR','','','','','','','151')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('178','GASOLINERO','','','','','','','152')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('179','PROMOTOR DE SALUD','','','','','','','153')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('180','PROFESOR INCESTIGADOR','','','','','','','154')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('181','DIRECTO DE PRIMARIA','','','','','','','155')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('182','GERENTE DE MODULO','','','','','','','156')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('183','CONSULTOR DE SISTEMAS','','','','','','','157')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('184','DIRECTOR DE ESCUELA PRIMARIA','','','','','','','158')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('185','MESERA','','','','','','','159')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('186','ADMINISTRACION ENCARGADO DE PRODUCCION','','','','','','','160')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('187','SUPERVISOR DE OBRA','','','','','','','161')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('188','DGA DE FINANZAS','','','','','','','162')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('189','MAESTRO DE GRUPO DE PRIMARIA FORANEO','','','','','','','163')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('190','JEFE DEPARTAMENTO JURIDICO','','','','','','','164')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('191','DIRECTOR DE VENTAS','','','','','','','165')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('192','CONTRALOR GENERAL','','','','','','','166')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('193','AMA DE LLAVES','','','','','','','167')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('194','MECANICO GENERAL','','','','','','','168')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('195','TOALLERA DE PISCINA','','','','','','','169')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('196','IMPRESOR','','','','','','','170')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('197','DIRECTOR CORPORATIVO','','','','','','','171')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('198','ENCARGADA ','','','','','','','172')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('199','JEFE DE SECCION','','','','','','','173')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('200','BELL BOY','','','','','','','174')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('201','BOTONES','','','','','','','175')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('202','ASESOR TECNICO EN DESARROLLO EDUCATIVO','','','','','','','176')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('203','TECNICO DE MANTENIMIENTO','','','','','','','177')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('204','OPERARIO PRODUCCION- HPC','','','','','','','178')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('205','COORDINADOR MEDICO EN AREA NORMATIVA "A"','','','','','','','179')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('206','SUPERVISOR TECNICO EN HIDRAULICA','','','','','','','180')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('207','SUPERVISION','','','','','','','181')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('208','DIRECTOR REGIONAL','','','','','','','182')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('209','INGENIERO','','','','','','','183')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('210','GERENTE DE DISEÑO INDUSTRIAL','','','','','','','184')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('211','COORDINADOR DE LA LIE','','','','','','','185')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('212','DIRECTOR GENERAL DE VIVIENDA','','','','','','','186')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('213','AGENTE DE SEGUROS','','','','','','','187')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('214','GERENTE OPERATIVO','','','','','','','188')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('215','ACADEMICO','','','','','','','189')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('216','TAQUERO','','','','','','','190')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('217','ASESOR FINANCIERO','','','','','','','191')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('218','RECEPCIONISTA','','','','','','','192')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('219','GERENTE DE MARCA JR','','','','','','','193')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('220','REPRESENTANTE DE  VENTAS','','','','','','','194')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('221','COORDINADOR DE CATALOGO','','','','','','','195')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('222','GERENTE DE OPERACIONES','','','','','','','196')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('223','TECNICO POLIVALENTE','','','','','','','197')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('224','AUXILIAR CONTABLE','','','','','','','198')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('225','CHOFER VENDEDOR','','','','','','','199')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('226','COCINERA','','','','','','','200')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('227','GERENTE DE CALIDAD Y PROCESOS ','','','','','','','201')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('228','MESERO BARES','','','','','','','202')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('229','LIDER DE PRODUCTOS DE LINEA','','','','','','','203')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('230','TECNICO DE VALIDACION','','','','','','','204')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('231','MAESTRA DE APOYO','','','','','','','205')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('232','ESQUIVADOR','','','','','','','206')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('233','GERENTE DE OBRA','','','','','','','207')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('234','ASESOR JURIDICO','','','','','','','208')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('235','SECRETARIO DE JUZGADO','','','','','','','209')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('236','STAFF DE VENTURA','','','','','','','210')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('237','ESPECIALISTA TECNICO','','','','','','','211')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('238','GERENTE DE CONCESIONES','','','','','','','212')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('239','CATEDRATICO','','','','','','','213')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('240','SACRISTAN','','','','','','','214')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('241','GUIA DE TURISTAS','','','','','','','215')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('242','DIRECTORA','','','','','','','216')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('243','BARMAN','','','','','','','217')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('244','AUXILIAR ADMINISTRATIVO','','','','','','','218')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('245','OFICIAL DE TRANSITO','','','','','','','219')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('246','AYUDANTE  GENERAL','','','','','','','220')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('247','VENDEDOR DE MOSTRADOR','','','','','','','221')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('248','COCINERO B','','','','','','','222')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('249','CAMARISTO','','','','','','','223')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('250','EMPACADORA','','','','','','','224')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('251','EMPACADORA DE SUSHI','','','','','','','225')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('252','DIRECTOR ADJUNTO','','','','','','','226')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('253','GERENTE DE CONTABILIDAD','','','','','','','227')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('254','GERENTE TECNICO','','','','','','','228')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('255','GERENTE COBRANZA','','','','','','','229')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('256','AUXILIAR PARAMEDICO','','','','','','','230')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('257','INTENDENTE','','','','','','','231')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('258','COORDINADORA DE COMUNICACION SOCIAL','','','','','','','232')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('259','CHOFER DE CAMION','','','','','','','233')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('260','COBRADOR','','','','','','','234')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('261','OFICIAL EXHUMADOR','','','','','','','235')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('262','JEFE DE ARCHIVO','','','','','','','236')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('263','ACTUARIO NOTIFICADOR','','','','','','','237')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('264','OPERADOR DE TRACTOCAMION','','','','','','','238')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('265','DELEGADO REGIONAL','','','','','','','239')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('266','RESERVACIONES Y VENTAS','','','','','','','240')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('267','PLANEADOR DE LA PRODUCCION','','','','','','','241')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('268','ADMINISTRATIVA','','','','','','','242')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('269','OFICIAL GASOLINERO','','','','','','','243')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('270','LANCHERO','','','','','','','244')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('271','EJE','','','','','','','245')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('272','PINTOR AUTOMOTRIZ','','','','','','','246')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('273','OPTOMETRISTA','','','','','','','247')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('274','EMPLEADA DOMESTICA','','','','','','','248')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('275','CARPINTERO Y EBANISTA','','','','','','','249')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('276','MAESTRO DE TELESECUNDARIA FORANEO','','','','','','','250')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('277','AYUDANTE DE BAR','','','','','','','251')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('278','ENCARGADO DE JARDINERIA','','','','','','','252')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('279','ARBITRO DE FUTBOL','','','','','','','253')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('280','INSTRUCTORA DE BELLEZA','','','','','','','254')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('281','COORDINADOR DE PROYECTOS','','','','','','','255')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('282','ALUMINERO','','','','','','','256')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('283','COORDINADORA DE PRESUPUESTOS Y MATERIALES','','','','','','','257')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('284','PRESIDENTE DEL CONSEJO DE ADMINISTRACION','','','','','','','258')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('285','VOCAL','','','','','','','259')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('286','PROPIETARIA','','','','','','','260')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('287','DESPACHADOR DE GASOLINA','','','','','','','261')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('288','ENFERMERA PARTICULAR','','','','','','','262')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('289','JARDINERO','','','','','','','263')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('290','NIÑERA','','','','','','','264')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('291','DISEÑADOR GRAFICO','','','','','','','265')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('292','CHOFER PARTICULAR','','','','','','','266')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('293','PROMOTORA DE LENTES','','','','','','','267')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('294','GARROTERO','','','','','','','268')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('295','RECAMARERA','','','','','','','269')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('296','INSPECTOR DE DAÑOS','','','','','','','270')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('297','CHOFER DE TAXI','','','','','','','271')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('298','INTENDENCIA','','','','','','','272')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('299','DESPACHADORA DE GASOLINA','','','','','','','273')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('300','ECONOMISTA','','','','','','','274')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('301','ESTILISTA','','','','','','','275')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('302','RESPONSABLE DE RANCHO','','','','','','','276')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('303','ASESOR GENERAL','','','','','','','277')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('304','DIRECTOR DE GESTION Y COBRANZA','','','','','','','278')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('305','ASISTENTE DE DIRECCION GENERAL','','','','','','','279')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('306','AUXILIAR DE SERVICIOS Y MANTENIMIENTO','','','','','','','280')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('307','ASISTENTE EDUCATIVO','','','','','','','281')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('308','SUPERVISOR GENERAL','','','','','','','282')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('309','VENTAS MOSTRADOR','','','','','','','283')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('310','CHOFER ','','','','','','','284')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('311','PROFESOR DE SECUNDARIA TECNICA','','','','','','','285')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('312','ASESOR DE OPERACIONES','','','','','','','286')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('313','INGENIERO CIVIL','','','','','','','287')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('314','INSTRUCTOR','','','','','','','288')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('315','ENTRENADOR DEPORTIVO','','','','','','','289')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('316','SUPERVISOR DE EMBARQUES','','','','','','','290')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('317','DIRECTOR DE ADMINISTRACION','','','','','','','291')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('318','DIRECCION DE COMERCIALIZACION','','','','','','','292')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('319','DIRECCION DE AREA TECNICA','','','','','','','293')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('320','ADMINISTRADOR DE PROYECTOS','','','','','','','294')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('321','DIRECTOR DE TITULACION','','','','','','','295')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('322','PRESIDENTE DE LOS ESTADOS UNIDOS MEXICANOS','','','','','','','296')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('323','CERRAJERO','','','','','','','297')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('324','ATENCION A CLIENTES','','','','','','','298')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('325','OFICIAL DE SEGURIDAD','','','','','','','299')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('326','ENSEÑANZA DE MODULOS PROFESIONALES','','','','','','','300')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('327','CHECADOR DE MATERIALES','','','','','','','301')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('328','AUXILIAR DE PRODUCCION','','','','','','','302')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('329','TECNICO','','','','','','','303')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('330','RESPONSABLE DE APOYOS ESPECIALES','','','','','','','304')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('331','AGENTE DE ESTACIONOMETROS','','','','','','','305')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('332','PROFESIONAL DE SERVICIOS ESPECIALIZADOS','','','','','','','306')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('333','ANIMADOR','','','','','','','307')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('334','PROFESORA DE INGLES','','','','','','','308')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('335','PROFESOR DE PRIMARIA','','','','','','','309')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('336','JUGUERIA','','','','','','','310')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('337','MANTENIMIENTO','','','','','','','311')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('338','BARISTA','','','','','','','312')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('339','PLOMERO','','','','','','','313')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('340','SOPORTE ADMINISTRATIVO F','','','','','','','314')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('341','REPORTERO','','','','','','','315')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('342','AUXILIAR DE ENFERMERIA','','','','','','','316')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('343','EMPLEADO DE MOSTRADOR','','','','','','','317')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('344','ARTESANO','','','','','','','318')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('345','TERAPEUTA','','','','','','','319')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('346','ESPECIALISTA EN TECNICAS DE LABORATORIO','','','','','','','320')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('347','FOTOGRAFO','','','','','','','321')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('348','CAPITAN DE BARCO','','','','','','','322')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('349','TECNICO ELECTRICISTA','','','','','','','323')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('350','TAXISTA','','','','','','','324')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('351','CONDUCTOR DE TAXI','','','','','','','325')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('352','ARRENDADOR','','','','','','','326')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('353','MEDICO ANESTESIOLOGO','','','','','','','327')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('354','OPERADOR DE MANTENIMIENTO','','','','','','','328')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('355','SUPERVISOR DE CONTROL DE INVENTARIOS','','','','','','','329')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('356','JEFE DEL AREA DE VINCULACION','','','','','','','330')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('357','GERENTE DE RESERVACIONES','','','','','','','331')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('358','PROFESOR DE EDUCACION MEDIA SUPERIOR','','','','','','','332')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('359','REP DE SERVICIOS A CLIENTES','','','','','','','333')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('360','PROYECTISTA','','','','','','','334')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('361','GERENTE DE RELACIONES PUBLICAS','','','','','','','335')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('362','ASOCIADO DE SERVICIO AL CLIENTE','','','','','','','336')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('363','MAESTRA','','','','','','','337')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('364','CUSTODIO ESPECIALIZADO EN ARQUEOLOGIA','','','','','','','338')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('365','MEDICO ESPECIALISTA EN SALUD EN EL TRABAJO','','','','','','','339')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('366','ENCARGADO GENERAL DE REPARTOS','','','','','','','340')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('367','SUPERVISOR DE VENTAS','','','','','','','341')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('368','PROFESOR DE ENSEÑANZA SECUNDARIA TECNICA FORANEO','','','','','','','342')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('369','ENCARGADO DE TIENDA','','','','','','','343')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('370','AUDITORA FINANCIERA','','','','','','','344')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('371','JEFA DE COCINA','','','','','','','345')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('372','PROFESOR DE ENSEÑANZA SECUNDARIA INGLES','','','','','','','346')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('373','PROMOVENDEDOR','','','','','','','347')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('374','QUIMICO C','','','','','','','348')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('375','SUPERVISOR DE EGRESOS','','','','','','','349')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('376','AGENTE DE POLICIA','','','','','','','350')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('377','COCINERO A','','','','','','','351')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('378','ANALISTA PROGRAMADOR B','','','','','','','352')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('379','MAESTRO DE SOCIALES','','','','','','','353')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('380','GERENTE DE PRODUCCION','','','','','','','354')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('381','GERENTE DE DISTRITO','','','','','','','355')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('382','EJECUTIVO DE CUENTA','','','','','','','356')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('383','CAPITAN DE MESEROS','','','','','','','357')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('384','CULTURA DE BELLEZA','','','','','','','358')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('385','OPERACIONES','','','','','','','359')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('386','SPA BUTLER','','','','','','','360')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('387','EMPLEADO','','','','','','','361')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('388','DESPACHADOR DE FARMACIA','','','','','','','362')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('389','DIBUJANTE','','','','','','','363')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('390','AYUDANTE AGENTE POST-MIX','','','','','','','364')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('391','ASISTENTE DE ALIMENTOS Y BEBIDAS','','','','','','','365')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('392','ENCARGADO DE ALIMENTOS Y BEBIDAS','','','','','','','366')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('393','CAPITAN MARINERO','','','','','','','367')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('394','INSTALADOR DE TABLAROCA, PINTURA Y OTROS TRABAJOS','','','','','','','368')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('395','EJECUTIVO MASTER DE VENTAS CAP','','','','','','','369')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('396','ASISTENTE ADMINISTRATIVO','','','','','','','370')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('397','ESTOMATOLOGO','','','','','','','371')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('398','PROFESOR TITULAR C EMS TC DF','','','','','','','372')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('399','LABORATORISTA','','','','','','','373')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('400','INGENIERO DE SERVICIO Y SOPORTE TECNICO','','','','','','','374')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('401','MAESTRO DE PREESCOLAR','','','','','','','375')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('402','COBRO DE RENTAS','','','','','','','376')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('403','TRANSPORTADOR DE ALIMENTOS','','','','','','','377')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('404','ASISTENTE DE VENTAS','','','','','','','378')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('405','SUB-CHEF','','','','','','','379')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('406','MEDICO ODONTOLOGO','','','','','','','380')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('407','OPERADOR DE CUARTOS','','','','','','','381')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('408','SUPERVISOR DE INSTALACIONES ','','','','','','','382')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('409','GERENTE DE CUENTA','','','','','','','383')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('410','AYUDANTE GENERAL','','','','','','','384')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('411','SUBJEFE DE FARMACIA','','','','','','','385')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('412','TECNICO EN PROGRAMAS DE SALUD','','','','','','','386')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('413','SUPERVISORA DE TIENDAS','','','','','','','387')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('414','JEFE DEPTO DE PERSONAL','','','','','','','388')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('415','ENFERMERA','','','','','','','389')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('416','AYUDANTE DE PROFESOR DE ASIGNATURA','','','','','','','390')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('417','COORDINADOR ESPECIALISTA B FUNCIONES ADMINISTRATIVAS','','','','','','','391')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('418','SUBDIRECTOR OPERATIVO','','','','','','','392')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('419','MAESTRA DE KINDER','','','','','','','393')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('420','AUDITOR INTERNO','','','','','','','394')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('421','ENCARGADA DE JURIDICO ','','','','','','','395')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('422','QUALITY ENGINEER','','','','','','','396')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('423','MAESTRO ENVOLVEDOR','','','','','','','397')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('424','COORDINADOR DE INVENTARIOS','','','','','','','398')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('425','EMPLEADO GENERAL','','','','','','','399')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('426','SOCIO Y CONSULTOR FISCAL','','','','','','','400')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('427','CONTRALOR ADMINISTRATIVO','','','','','','','401')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('428','TECNICO PLOMERO','','','','','','','402')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('429','SOLDADOR','','','','','','','403')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('430','ENCARGADO DE ALMACEN','','','','','','','404')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('431','COORDINADOR DE VENTAS','','','','','','','405')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('432','VENDEDOR DE VENTAS PYMES','','','','','','','406')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('433','DIRECTOR DE OBRAS PUBLICAS ADMINISTRATIVO','','','','','','','407')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('434','ANALISTA DE AUDITORIA','','','','','','','408')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('435','AUXILIAR DE REFINERIA','','','','','','','409')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('436','ANALISTA DE ACTIVO','','','','','','','410')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('437','AUXILIAR TECNICO','','','','','','','411')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('438','ADMINISTRATIVO','','','','','','','412')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('439','SUBJEFE DE PLANEACION','','','','','','','413')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('440','TECNICO EN PROYECTOS','','','','','','','414')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('441','RESIDENTE DE OBRA','','','','','','','415')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('442','APOYO ADMINISTRATIVO','','','','','','','416')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('443','OFICIAL ELECTRICO','','','','','','','417')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('444','ATENCION A CLIENTES POSVENTA','','','','','','','418')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('445','ASESOR DE VENTAS','','','','','','','419')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('446','MAESTRO DE INGLES','','','','','','','420')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('447','DUEÑA','','','','','','','421')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('448','COORDINADOR Y SUPERVISOR DE OBRA','','','','','','','422')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('449','SUBDIRECTOR DE GIRAS PRESIDENCIALES','','','','','','','423')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('450','SOCIO INDUSTRIAL COORDINADOR Y VENTAS TIEMPO COMPARTIDOS','','','','','','','424')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('451','ASISTENTE MEDICO','','','','','','','425')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('452','GUEST SERVICE','','','','','','','426')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('453','CHEF PASTELERO','','','','','','','427')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('454','DEMOSTRADORA','','','','','','','428')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('455','MANTENIMIENTO Y REMODELACIONES','','','','','','','429')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('456','PARRILLERO','','','','','','','430')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('457','RENTA DE SISTEMAS DE COMPUTO','','','','','','','431')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('458','PROMOTOR ','','','','','','','432')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('459','JEFE DE DEPARTAMENTO','','','','','','','433')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('460','AUXILIAR DE ALBAÑIL','','','','','','','434')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('461','DOMESTICA','','','','','','','435')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('462','JUGADOR PROFESIONAL','','','','','','','436')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('463','AUXILIAR DE RESIDENTE','','','','','','','437')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('464','TECNICO ALUMBRADO','','','','','','','438')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('465','FUTBOLISTA PROFESIONAL','','','','','','','439')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('466','CONTRATISTA','','','','','','','440')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('467','EMPPLEADA DOMESTICA','','','','','','','441')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('468','OPERADOR DE CAMION DE VOLTEO','','','','','','','442')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('469','BARRENDERO','','','','','','','443')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('470','OFICIAL DE ALBAÑILERIA','','','','','','','444')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('471','GERENTE DE CONCIERGE','','','','','','','445')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('472','ASESORA DE VENTAS','','','','','','','446')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('473','CATEGORIA A','','','','','','','447')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('474','MANTENIMIENTO URBANO','','','','','','','448')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('475','AZULEJERO','','','','','','','449')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('476','AYUDANTE DE VULCANIZADORA','','','','','','','450')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('477','VENDEDORA','','','','','','','451')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('478','YESERO','','','','','','','452')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('479','SOCIO Y EMPLEADO','','','','','','','453')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('480','TORTILLERO','','','','','','','454')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('481','LAMINERO','','','','','','','455')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('482','COSTURERA','','','','','','','456')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('483','MENSAJERO Y VIGILANTE','','','','','','','457')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('484','LAVA AUTOS','','','','','','','458')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('485','CARPINTERO','','','','','','','459')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('486','ASESOR COMERCIAL Y COORDINADOR','','','','','','','460')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('487','OPERATIVO','','','','','','','461')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('488','INSTALADOR Y PULIDOR DE PISOS','','','','','','','462')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('489','MAESTRO DE OBRAS','','','','','','','463')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('490','MECANICO ARMADOR','','','','','','','464')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('491','PINTOR','','','','','','','465')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('492','AUXILIAR JURIDICO','','','','','','','466')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('493','GUARDIA DE SEGURIDAD','','','','','','','467')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('494','TATUADOR','','','','','','','468')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('495','PROPIETARIA DE NEGOCIO','','','','','','','469')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('496','PRESIDENTE EJECUTIVO','','','','','','','470')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('497','VENTA DE CERAMICA Y MANUALIDADES','','','','','','','471')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('498','PROFESOR TITULADO','','','','','','','472')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('499','SUBDIRECCION COMERCIAL DE TERRENOS UNIFAMILIARES','','','','','','','473')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('500','SUPERVISOR DE RECEPCION','','','','','','','474')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('501','INGENIERO DE PREVENTAS PRINCIPAL','','','','','','','475')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('502','PROSECRETARIO','','','','','','','476')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('503','CONSEJERO PROPIETARIO','','','','','','','477')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('504','CONSEJERO SUPLENTE','','','','','','','478')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('505','ASESOR INMOBILIARIO','','','','','','','479')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('506','ENFERMERO','','','','','','','480')
INSERT INTO CLPUESTO (Pue_Numero, Pue_Descri, NumTransac, Transaccio, Usuario, FechaSis, SucOrigen, SucDestino, Rel_SIHCEI)  VALUES ('507','OFICIAL ADMINISTRATIVO','','','','','','','481')
