#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPLD")]
	public partial class ListaNegraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ListaNegraDataContext() : 
				base(global::BIM.PLD.DataAccess.Properties.Settings.Default.dbPLDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ListaNegraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaNegraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaNegraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaNegraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarSistemasPLD")]
		public ISingleResult<stp_ListarSistemasPLDResult> stp_ListarSistemasPLD()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarSistemasPLDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_InsertaListaNegra")]
		public int stp_InsertaListaNegra(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchidqeq, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string vchTipoLista, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string vchNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string vchApPaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string vchApMaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchCURP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchRFC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchFechaNac, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchEstatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(120)")] string vchDependencia, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(120)")] string vchPuesto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string intIDdispo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string bitCurpOK, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(120)")] string vchIDRel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(120)")] string vchParentesco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchRazonSocial, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(140)")] string vchRFCMoral, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string vchISSSTE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string vchIMSS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(180)")] string vchIngresos, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3000)")] string vchNomCompleto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string vchApellidos, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string vchEntidad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchGenero, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(180)")] string vchAudUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> sdatFechains, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3000)")] string vchCadenaNPM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3000)")] string vchCadenaNMP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vchidqeq, vchTipoLista, vchNombre, vchApPaterno, vchApMaterno, vchCURP, vchRFC, vchFechaNac, vchEstatus, vchDependencia, vchPuesto, intIDdispo, bitCurpOK, vchIDRel, vchParentesco, vchRazonSocial, vchRFCMoral, vchISSSTE, vchIMSS, vchIngresos, vchNomCompleto, vchApellidos, vchEntidad, vchGenero, vchAudUsuario, sdatFechains, vchCadenaNPM, vchCadenaNMP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarProveedores")]
		public ISingleResult<stp_ListarProveedoresResult> stp_ListarProveedores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarProveedoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarTipoLista")]
		public ISingleResult<stp_ListarTipoListaResult> stp_ListarTipoLista()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarTipoListaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_InsertarTipoLista")]
		public ISingleResult<stp_InsertarTipoListaResult> stp_InsertarTipoLista([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string vchTipoLista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoTipificacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VCDDESCRIPCION", DbType="VarChar(256)")] string vCDDESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string vchPais)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, vchTipoLista, intTipoTipificacionID, vCDDESCRIPCION, vchPais);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_InsertarTipoListaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_CargaListasNegras")]
		public ISingleResult<stp_CargaListasNegrasResult> stp_CargaListasNegras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string mensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iProveedorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mensaje, iProveedorId);
			mensaje = ((string)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_CargaListasNegrasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_InsertaProveedor")]
		public int stp_InsertaProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vchProveedor);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarSistemasPLDResult
	{
		
		private short _sintSistemaID;
		
		private string _vchNombre;
		
		private string _vchDescripcion;
		
		private int _conf;
		
		public stp_ListarSistemasPLDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintSistemaID", DbType="SmallInt NOT NULL")]
		public short sintSistemaID
		{
			get
			{
				return this._sintSistemaID;
			}
			set
			{
				if ((this._sintSistemaID != value))
				{
					this._sintSistemaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vchNombre
		{
			get
			{
				return this._vchNombre;
			}
			set
			{
				if ((this._vchNombre != value))
				{
					this._vchNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(200)")]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conf", DbType="Int NOT NULL")]
		public int conf
		{
			get
			{
				return this._conf;
			}
			set
			{
				if ((this._conf != value))
				{
					this._conf = value;
				}
			}
		}
	}
	
	public partial class stp_ListarProveedoresResult
	{
		
		private int _iProveedorId;
		
		private string _vchDescripcion;
		
		public stp_ListarProveedoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProveedorId", DbType="Int NOT NULL")]
		public int iProveedorId
		{
			get
			{
				return this._iProveedorId;
			}
			set
			{
				if ((this._iProveedorId != value))
				{
					this._iProveedorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(100)")]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_ListarTipoListaResult
	{
		
		private string _vchTipoLista;
		
		public stp_ListarTipoListaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoLista", DbType="NVarChar(10)")]
		public string vchTipoLista
		{
			get
			{
				return this._vchTipoLista;
			}
			set
			{
				if ((this._vchTipoLista != value))
				{
					this._vchTipoLista = value;
				}
			}
		}
	}
	
	public partial class stp_InsertarTipoListaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public stp_InsertarTipoListaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class stp_CargaListasNegrasResult
	{
		
		private string _Column1;
		
		public stp_CargaListasNegrasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(200)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
