#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPLD")]
	public partial class TipoCambioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public TipoCambioDataContext() :
        base(global::BIM.PLD.DataAccess.Properties.Settings.Default.dbPLDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TipoCambioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TipoCambioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TipoCambioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TipoCambioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_getTipoCambio")]
		public ISingleResult<stp_getTipoCambioResult> stp_getTipoCambio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_getTipoCambioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_InsertaTipoCambioManual")]
		public int stp_InsertaTipoCambioManual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCierre", DbType="Date")] System.Nullable<System.DateTime> fechaCierre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(15,2)")] System.Nullable<decimal> decValor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaCierre, decValor);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class stp_getTipoCambioResult
	{
		
		private string _vchDescripcionCMO;
		
		private string _vchDescripcionCGE;
		
		private decimal _decValorCTC;
		
		private System.DateTime _datFchDeCierreCTC;
		
		public stp_getTipoCambioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcionCMO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vchDescripcionCMO
		{
			get
			{
				return this._vchDescripcionCMO;
			}
			set
			{
				if ((this._vchDescripcionCMO != value))
				{
					this._vchDescripcionCMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcionCGE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vchDescripcionCGE
		{
			get
			{
				return this._vchDescripcionCGE;
			}
			set
			{
				if ((this._vchDescripcionCGE != value))
				{
					this._vchDescripcionCGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decValorCTC", DbType="Decimal(18,4) NOT NULL")]
		public decimal decValorCTC
		{
			get
			{
				return this._decValorCTC;
			}
			set
			{
				if ((this._decValorCTC != value))
				{
					this._decValorCTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFchDeCierreCTC", DbType="DateTime NOT NULL")]
		public System.DateTime datFchDeCierreCTC
		{
			get
			{
				return this._datFchDeCierreCTC;
			}
			set
			{
				if ((this._datFchDeCierreCTC != value))
				{
					this._datFchDeCierreCTC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
