#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPLD")]
	public partial class VerificadorPDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public VerificadorPDLDataContext() : 
				base(global::BIM.PLD.DataAccess.Properties.Settings.Default.dbPLDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VerificadorPDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerificadorPDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerificadorPDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerificadorPDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_BuscarListaNegra")]
		public ISingleResult<stp_BuscarListaNegraResult> stp_BuscarListaNegra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchPersonaIncidenciaNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchPersonaIncidenciaApPat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchPersonaIncidenciaApMat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string vchNombreCompleto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vchPersonaIncidenciaNombre, vchPersonaIncidenciaApPat, vchPersonaIncidenciaApMat, vchNombreCompleto);
			return ((ISingleResult<stp_BuscarListaNegraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_DesbloquearUsuario")]
		public int stp_DesbloquearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string vchUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vchUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_CRUDBitacoraPLD")]
		public ISingleResult<stp_CRUDBitacoraPLDResult> stp_CRUDBitacoraPLD(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intAccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intBitacoraID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchidqeq, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string vchUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string vchSucursal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intSistema, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchPersonaIncidencia, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchApPaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchApMaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string vchNombreBusq, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchCliente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchRelacionCliente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string vchComentario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitAutorizaProc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> datFecha, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitHomonimo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitEstatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitHistorial, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string vchUsuarioAudit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, intAccion, intBitacoraID, vchidqeq, vchUsuario, vchSucursal, intSistema, vchPersonaIncidencia, vchNombre, vchApPaterno, vchApMaterno, vchNombreBusq, vchCliente, vchRelacionCliente, vchComentario, bitAutorizaProc, datFecha, bitHomonimo, bitEstatus, bitHistorial, vchUsuarioAudit);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_CRUDBitacoraPLDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class stp_BuscarListaNegraResult
	{
		
		private string _VCHIDQEQ;
		
		private string _VCHTIPOLISTA;
		
		private int _intTipoTipificacionID;
		
		private string _vchIdentificadorInterno;
		
		private string _VCHNOMCOMPLETO;
		
		public stp_BuscarListaNegraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCHIDQEQ", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string VCHIDQEQ
		{
			get
			{
				return this._VCHIDQEQ;
			}
			set
			{
				if ((this._VCHIDQEQ != value))
				{
					this._VCHIDQEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCHTIPOLISTA", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string VCHTIPOLISTA
		{
			get
			{
				return this._VCHTIPOLISTA;
			}
			set
			{
				if ((this._VCHTIPOLISTA != value))
				{
					this._VCHTIPOLISTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoTipificacionID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int intTipoTipificacionID
		{
			get
			{
				return this._intTipoTipificacionID;
			}
			set
			{
				if ((this._intTipoTipificacionID != value))
				{
					this._intTipoTipificacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchIdentificadorInterno", DbType="VarChar(25)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string vchIdentificadorInterno
		{
			get
			{
				return this._vchIdentificadorInterno;
			}
			set
			{
				if ((this._vchIdentificadorInterno != value))
				{
					this._vchIdentificadorInterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCHNOMCOMPLETO", DbType="VarChar(3000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string VCHNOMCOMPLETO
		{
			get
			{
				return this._VCHNOMCOMPLETO;
			}
			set
			{
				if ((this._VCHNOMCOMPLETO != value))
				{
					this._VCHNOMCOMPLETO = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class stp_CRUDBitacoraPLDResult
	{
		
		private int _intBitacoraID;
		
		private string _vchidqeq;
		
		private string _vchUsuario;
		
		private string _vchUsuarioNombre;
		
		private string _vchSucursal;
		
		private System.Nullable<int> _intSistema;
		
		private string _vchPersonaIncidencia;
		
		private string _vchNombre;
		
		private string _vchApPaterno;
		
		private string _vchApMaterno;
		
		private string _vchNombreBusq;
		
		private string _vchCliente;
		
		private string _vchRelacionCliente;
		
		private string _vchComentario;
		
		private System.Nullable<bool> _bitAutorizaProc;
		
		private System.Nullable<System.DateTime> _datFecha;
		
		private System.Nullable<System.DateTime> _datFechaRespuesta;
		
		private System.Nullable<bool> _bitHomonimo;
		
		private string _vchUsuarioAudit;
		
		private System.Nullable<bool> _bitEstatus;
		
		private string _vchNombreSistema;
		
		private string _vchTipoLista;
		
		private int _intTipoTipificacionID;
		
		private string _vchIdentificadorInterno;
		
		private string _vchCorreoHCM;
		
		public stp_CRUDBitacoraPLDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBitacoraID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int intBitacoraID
		{
			get
			{
				return this._intBitacoraID;
			}
			set
			{
				if ((this._intBitacoraID != value))
				{
					this._intBitacoraID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchidqeq", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string vchidqeq
		{
			get
			{
				return this._vchidqeq;
			}
			set
			{
				if ((this._vchidqeq != value))
				{
					this._vchidqeq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchUsuario", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string vchUsuario
		{
			get
			{
				return this._vchUsuario;
			}
			set
			{
				if ((this._vchUsuario != value))
				{
					this._vchUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchUsuarioNombre", DbType="VarChar(152)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string vchUsuarioNombre
		{
			get
			{
				return this._vchUsuarioNombre;
			}
			set
			{
				if ((this._vchUsuarioNombre != value))
				{
					this._vchUsuarioNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchSucursal", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string vchSucursal
		{
			get
			{
				return this._vchSucursal;
			}
			set
			{
				if ((this._vchSucursal != value))
				{
					this._vchSucursal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSistema", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> intSistema
		{
			get
			{
				return this._intSistema;
			}
			set
			{
				if ((this._intSistema != value))
				{
					this._intSistema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPersonaIncidencia", DbType="VarChar(302)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string vchPersonaIncidencia
		{
			get
			{
				return this._vchPersonaIncidencia;
			}
			set
			{
				if ((this._vchPersonaIncidencia != value))
				{
					this._vchPersonaIncidencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombre", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string vchNombre
		{
			get
			{
				return this._vchNombre;
			}
			set
			{
				if ((this._vchNombre != value))
				{
					this._vchNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchApPaterno", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string vchApPaterno
		{
			get
			{
				return this._vchApPaterno;
			}
			set
			{
				if ((this._vchApPaterno != value))
				{
					this._vchApPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchApMaterno", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string vchApMaterno
		{
			get
			{
				return this._vchApMaterno;
			}
			set
			{
				if ((this._vchApMaterno != value))
				{
					this._vchApMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombreBusq", DbType="VarChar(300)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string vchNombreBusq
		{
			get
			{
				return this._vchNombreBusq;
			}
			set
			{
				if ((this._vchNombreBusq != value))
				{
					this._vchNombreBusq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCliente", DbType="VarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string vchCliente
		{
			get
			{
				return this._vchCliente;
			}
			set
			{
				if ((this._vchCliente != value))
				{
					this._vchCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchRelacionCliente", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string vchRelacionCliente
		{
			get
			{
				return this._vchRelacionCliente;
			}
			set
			{
				if ((this._vchRelacionCliente != value))
				{
					this._vchRelacionCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchComentario", DbType="VarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string vchComentario
		{
			get
			{
				return this._vchComentario;
			}
			set
			{
				if ((this._vchComentario != value))
				{
					this._vchComentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitAutorizaProc", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<bool> bitAutorizaProc
		{
			get
			{
				return this._bitAutorizaProc;
			}
			set
			{
				if ((this._bitAutorizaProc != value))
				{
					this._bitAutorizaProc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFecha", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<System.DateTime> datFecha
		{
			get
			{
				return this._datFecha;
			}
			set
			{
				if ((this._datFecha != value))
				{
					this._datFecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaRespuesta", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<System.DateTime> datFechaRespuesta
		{
			get
			{
				return this._datFechaRespuesta;
			}
			set
			{
				if ((this._datFechaRespuesta != value))
				{
					this._datFechaRespuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitHomonimo", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<bool> bitHomonimo
		{
			get
			{
				return this._bitHomonimo;
			}
			set
			{
				if ((this._bitHomonimo != value))
				{
					this._bitHomonimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchUsuarioAudit", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public string vchUsuarioAudit
		{
			get
			{
				return this._vchUsuarioAudit;
			}
			set
			{
				if ((this._vchUsuarioAudit != value))
				{
					this._vchUsuarioAudit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitEstatus", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<bool> bitEstatus
		{
			get
			{
				return this._bitEstatus;
			}
			set
			{
				if ((this._bitEstatus != value))
				{
					this._bitEstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombreSistema", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string vchNombreSistema
		{
			get
			{
				return this._vchNombreSistema;
			}
			set
			{
				if ((this._vchNombreSistema != value))
				{
					this._vchNombreSistema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoLista", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public string vchTipoLista
		{
			get
			{
				return this._vchTipoLista;
			}
			set
			{
				if ((this._vchTipoLista != value))
				{
					this._vchTipoLista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoTipificacionID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public int intTipoTipificacionID
		{
			get
			{
				return this._intTipoTipificacionID;
			}
			set
			{
				if ((this._intTipoTipificacionID != value))
				{
					this._intTipoTipificacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchIdentificadorInterno", DbType="VarChar(25)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public string vchIdentificadorInterno
		{
			get
			{
				return this._vchIdentificadorInterno;
			}
			set
			{
				if ((this._vchIdentificadorInterno != value))
				{
					this._vchIdentificadorInterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCorreoHCM", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=25)]
		public string vchCorreoHCM
		{
			get
			{
				return this._vchCorreoHCM;
			}
			set
			{
				if ((this._vchCorreoHCM != value))
				{
					this._vchCorreoHCM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
