INSERT INTO tbl_CAT_TipoTipificacion (vchDescripcion) VALUES ('NORMAL')
INSERT INTO tbl_CAT_TipoTipificacion (vchDescripcion) VALUES ('PEP')
INSERT INTO tbl_CAT_TipoTipificacion (vchDescripcion) VALUES ('VENC')
INSERT INTO tbl_CAT_TipoTipificacion (vchDescripcion) VALUES ('NEGRA')
INSERT INTO tbl_CAT_TipoTipificacion (vchDescripcion) VALUES ('INDEFINIDO')