INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('AQ','4','Al Qaida', '')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('ATF','4','Bureau of Alcohol, Tobacco, Firearms and Explosives', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('BID','4','Banco Interamericano de Desarrollo', 'America Latina')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('BIS','4','Bureau of Industry and Security', 'EstadosUnidos')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('BM','4','Banco Mundial', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('BOE','4','Bank of England', 'Inglaterra')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('CBI','4','Central Bureau of Investigation', 'India')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('DEA','4','Drug Enforcement Administration', 'EstadosUnidos')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('EPA','4','Environmental Protection Agency', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('FAMI','2','Familiares de los Funcionarios', 'México')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('FBI','4','Federal Bureau of Investigation', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('FUNC','2','Funcionarios que trabajan en el Gobierno (que no son 2S)', 'México')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('HMT','4','Her Majesty''s Treasury', 'Reino Unido')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('INTP','4','Interpol - Organización Internacional de Policía Criminal', 'Internacional')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('LMW','4','London Most Wanted', 'Reino Unido')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('OFAC','4','Office of  Foreingn Assets Control', 'EstadosUnidos')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('OSFI','4','Office of the Superintendent of Financial Institutions', 'Canadá')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('PGJ','4','Procuraduría General de Justicia', 'México')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('PGR','4','Procuraduría General de la República', 'México')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('PIS','4','Postal Inspection Service', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('PPE','2','Personas Expuestas Políticamente con Familiares y Consanguíneos', 'México')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('SSEU','4','Secret Service', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('UKMV','4','United Kingdom Most Wanted', 'Reino Unido')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('USMS','4','U.S. Marshals Service', 'EUA')
INSERT INTO tbl_CAT_TipoListaNegra (vchTipoLista, intTipoTipificacionID, VCDDESCRIPCION, vchPais) VALUES ('VENC','3','Vencidos', 'México')