//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.PLD.Website.CatalogosServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catalogo", Namespace="http://schemas.datacontract.org/2004/07/BIM.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Catalogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCatalogoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchClaveCNBVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blPadre {
            get {
                return this.blPadreField;
            }
            set {
                if ((this.blPadreField.Equals(value) != true)) {
                    this.blPadreField = value;
                    this.RaisePropertyChanged("blPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCatalogoID {
            get {
                return this.intCatalogoIDField;
            }
            set {
                if ((this.intCatalogoIDField.Equals(value) != true)) {
                    this.intCatalogoIDField = value;
                    this.RaisePropertyChanged("intCatalogoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchClaveCNBV {
            get {
                return this.vchClaveCNBVField;
            }
            set {
                if ((object.ReferenceEquals(this.vchClaveCNBVField, value) != true)) {
                    this.vchClaveCNBVField = value;
                    this.RaisePropertyChanged("vchClaveCNBV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchDescripcion {
            get {
                return this.vchDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.vchDescripcionField, value) != true)) {
                    this.vchDescripcionField = value;
                    this.RaisePropertyChanged("vchDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogosServices.ICatalogoServices")]
    public interface ICatalogoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/ListarCatalogoTipoListaNegra", ReplyAction="http://tempuri.org/ICatalogoServices/ListarCatalogoTipoListaNegraResponse")]
        BIM.PLD.Website.CatalogosServices.Catalogo[] ListarCatalogoTipoListaNegra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/ListadoCatAccionesPLD", ReplyAction="http://tempuri.org/ICatalogoServices/ListadoCatAccionesPLDResponse")]
        BIM.PLD.Website.CatalogosServices.Catalogo[] ListadoCatAccionesPLD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/ListadoCatTipoLista", ReplyAction="http://tempuri.org/ICatalogoServices/ListadoCatTipoListaResponse")]
        BIM.PLD.Website.CatalogosServices.Catalogo[] ListadoCatTipoLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/ListaBusquedaInteligenteTipoTipificacion", ReplyAction="http://tempuri.org/ICatalogoServices/ListaBusquedaInteligenteTipoTipificacionResp" +
            "onse")]
        BIM.PLD.Website.CatalogosServices.Catalogo[] ListaBusquedaInteligenteTipoTipificacion(string strDatos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoServicesChannel : BIM.PLD.Website.CatalogosServices.ICatalogoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoServicesClient : System.ServiceModel.ClientBase<BIM.PLD.Website.CatalogosServices.ICatalogoServices>, BIM.PLD.Website.CatalogosServices.ICatalogoServices {
        
        public CatalogoServicesClient() {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BIM.PLD.Website.CatalogosServices.Catalogo[] ListarCatalogoTipoListaNegra() {
            return base.Channel.ListarCatalogoTipoListaNegra();
        }
        
        public BIM.PLD.Website.CatalogosServices.Catalogo[] ListadoCatAccionesPLD() {
            return base.Channel.ListadoCatAccionesPLD();
        }
        
        public BIM.PLD.Website.CatalogosServices.Catalogo[] ListadoCatTipoLista() {
            return base.Channel.ListadoCatTipoLista();
        }
        
        public BIM.PLD.Website.CatalogosServices.Catalogo[] ListaBusquedaInteligenteTipoTipificacion(string strDatos) {
            return base.Channel.ListaBusquedaInteligenteTipoTipificacion(strDatos);
        }
    }
}
